{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.132",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.132.jar",
          "url": "alchemy-1.20.1-0.1.132.jar",
          "size": 1693185,
          "sha512": "8ac65e8c8c4d43a885b065565b566514f9491a4d7beb93e5db593c42e8441a421ee75fc2b6bcd354c0317b043f0bc5d56bb6cd9a08ca05e426b75b625dc00808",
          "sha256": "f3c2373b26ed55f028a60fb441b67ab556ccee09e7201666c99cf933d6ba9e61",
          "sha1": "a344a86b3dacbb7a00ad8e0968c78abcd78b1e75",
          "md5": "bb639865ad24fc69aa26887532a07689"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.132.jar",
          "url": "alchemy-1.20.1-0.1.132.jar",
          "size": 1693185,
          "sha512": "8ac65e8c8c4d43a885b065565b566514f9491a4d7beb93e5db593c42e8441a421ee75fc2b6bcd354c0317b043f0bc5d56bb6cd9a08ca05e426b75b625dc00808",
          "sha256": "f3c2373b26ed55f028a60fb441b67ab556ccee09e7201666c99cf933d6ba9e61",
          "sha1": "a344a86b3dacbb7a00ad8e0968c78abcd78b1e75",
          "md5": "bb639865ad24fc69aa26887532a07689"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.132-sources.jar",
          "url": "alchemy-1.20.1-0.1.132-sources.jar",
          "size": 1680945,
          "sha512": "bdb1745be7f4b5aef865d236b84c641a43d4dddb20267414e70aa0ac48578a4b396af812fb9787bde82b6a100d3f9cd9a9277646f1079ecc93e8be1c58c403d8",
          "sha256": "adba58411012090e7b1b2881f5b525c2a91c33b2fb6a8c20f4bf655a93cf3ee1",
          "sha1": "ae53ce3699a664ecdbcf156714b922fb950e5a14",
          "md5": "686db7fd852bc5b354921351ad4d9dde"
        }
      ]
    }
  ]
}
