{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.8-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.8-Fabric.jar",
          "url": "maple-1.20.1-1.4.8-Fabric.jar",
          "size": 1885653,
          "sha512": "ee91f12d916f92abcd605a576eb65de6f572ae4ba0ba6555865fe2e30bb602223a3383d2abb5f2ed8de7ae534e58c64e08ec3958aab6085d441a5fca1438de29",
          "sha256": "2ab42ecfbc3477b0ca8db5b57c7832260f94240075279a54b6bb648fe9e8c751",
          "sha1": "724d7f176919da478df8e15e99414a4249cfce37",
          "md5": "0fa38ce47a60deb1dfbf12d8b3b7e7da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.8-Fabric.jar",
          "url": "maple-1.20.1-1.4.8-Fabric.jar",
          "size": 1885653,
          "sha512": "ee91f12d916f92abcd605a576eb65de6f572ae4ba0ba6555865fe2e30bb602223a3383d2abb5f2ed8de7ae534e58c64e08ec3958aab6085d441a5fca1438de29",
          "sha256": "2ab42ecfbc3477b0ca8db5b57c7832260f94240075279a54b6bb648fe9e8c751",
          "sha1": "724d7f176919da478df8e15e99414a4249cfce37",
          "md5": "0fa38ce47a60deb1dfbf12d8b3b7e7da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.8-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.8-Fabric-sources.jar",
          "size": 1882530,
          "sha512": "13c532a08b7ab6630c8ff5223d1755b1973055cb5c112e2ec38023de4022c504b4abb3eb7c0da258320767e759a24ffb09e3519a97498b4db4b31e0e054c5ad0",
          "sha256": "5b6b018540add92b6a884346f45b1d6dfde9fdb2344a76eb699892b1504bcf2a",
          "sha1": "8d00b091eb7dbe9a98ee4a2d8608eeafd5de0696",
          "md5": "94729ad9029e59e5b2f71d20ed9e3d1b"
        }
      ]
    }
  ]
}
