{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "UsefulFood_Reborn",
    "version": "1.0.0-1.20.1-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric.jar",
          "url": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric.jar",
          "size": 290988,
          "sha512": "8c74184faae79f735dedc6e5d7d510cbd2eeb6c5f69b6181ca0e06adbea045b497d22a3f04b12cdc4afc93a79ae416b62626418de87435eb88be113d73ad99b0",
          "sha256": "a5fba250e5df0fbd04d9b58a78abf9f9a439dddacd05e7bedd765cfc6744fd56",
          "sha1": "3c68b6a52186e1c82e66d1022a4725e5b32267a6",
          "md5": "9bd6817ed4a877615913a65111233bc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.22"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric.jar",
          "url": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric.jar",
          "size": 290988,
          "sha512": "8c74184faae79f735dedc6e5d7d510cbd2eeb6c5f69b6181ca0e06adbea045b497d22a3f04b12cdc4afc93a79ae416b62626418de87435eb88be113d73ad99b0",
          "sha256": "a5fba250e5df0fbd04d9b58a78abf9f9a439dddacd05e7bedd765cfc6744fd56",
          "sha1": "3c68b6a52186e1c82e66d1022a4725e5b32267a6",
          "md5": "9bd6817ed4a877615913a65111233bc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric-sources.jar",
          "url": "UsefulFood_Reborn-1.0.0-1.20.1-Fabric-sources.jar",
          "size": 293025,
          "sha512": "1553b98f6690faf71af21d01bd244eb7c75caad5a5786344dc58aa8ebe64c5c41ecca5c34797f1a563314e59bee77d340d66ca5b3c510e69a6dc45df6e34b2ed",
          "sha256": "6bfaf54abba8f1d3ed65bbe313677cbc00373907793dcdfce90ef4495a918f4b",
          "sha1": "ec06fd6b82a584aced9c7f1b5ddc850272097e51",
          "md5": "604597660547eb174d8397dec3544e30"
        }
      ]
    }
  ]
}
