{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.139",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.139.jar",
          "url": "alchemy-1.20.1-0.1.139.jar",
          "size": 1693164,
          "sha512": "00ac342b32968ad5418975e0b16c0de80a097e4f59832bf9d376a1228341341ae603f70cd4b622808c7f40672b9688ae7816040560c56b573abde9bb7858f507",
          "sha256": "dc2fc61b248e2e3eed0104bde27d9e60e9e98b70f4da345adbfb01c06355520a",
          "sha1": "9c054b5edf3b93d83b16239bc425a6537e304aae",
          "md5": "1ac761862251e2bded91f4b5f765aac8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.139.jar",
          "url": "alchemy-1.20.1-0.1.139.jar",
          "size": 1693164,
          "sha512": "00ac342b32968ad5418975e0b16c0de80a097e4f59832bf9d376a1228341341ae603f70cd4b622808c7f40672b9688ae7816040560c56b573abde9bb7858f507",
          "sha256": "dc2fc61b248e2e3eed0104bde27d9e60e9e98b70f4da345adbfb01c06355520a",
          "sha1": "9c054b5edf3b93d83b16239bc425a6537e304aae",
          "md5": "1ac761862251e2bded91f4b5f765aac8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.139-sources.jar",
          "url": "alchemy-1.20.1-0.1.139-sources.jar",
          "size": 1680351,
          "sha512": "b0e7c2780d16911f6d9c73dc2f229e4e37b3879f000a885bb0506efb6b7d342555ba5133a63c8afc9e0ee385bf33cdc9948a225b72058cf25201a85235434750",
          "sha256": "cb8adda4dd4f984c3d0cf26ba586f78d53459b7e8206b71a21a90c7aa96779e0",
          "sha1": "8911b9aec328c38feace5c4be3ef53c3c1313ae1",
          "md5": "95f6b9cb93f0fde4efe1e64a142925bf"
        }
      ]
    }
  ]
}
