{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta15-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta15-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta15-Fabric.jar",
          "size": 1175653,
          "sha512": "79c03350ef449eaf9f397a9a879602e0d3a7069d27145dfe8f2d3b064b57e7c9d9002ec158fd502b91e37da199a6dda7ec1e9abd6f86ab9c42168ad4f68c2122",
          "sha256": "e1d8a09fb94d72b47964ff13fe550765f3d9e029d2fad6272ffee8ce4a9b611e",
          "sha1": "b7cad383d8b5f255dd84e385b631c201cce53de2",
          "md5": "5e97afe4aafbaf3302526d77a72e69d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta15-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta15-Fabric.jar",
          "size": 1175653,
          "sha512": "79c03350ef449eaf9f397a9a879602e0d3a7069d27145dfe8f2d3b064b57e7c9d9002ec158fd502b91e37da199a6dda7ec1e9abd6f86ab9c42168ad4f68c2122",
          "sha256": "e1d8a09fb94d72b47964ff13fe550765f3d9e029d2fad6272ffee8ce4a9b611e",
          "sha1": "b7cad383d8b5f255dd84e385b631c201cce53de2",
          "md5": "5e97afe4aafbaf3302526d77a72e69d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta15-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta15-Fabric-sources.jar",
          "size": 1112848,
          "sha512": "4cd96fe6528ecb94a22acfeb165194bcf2b7df92e8109942c1caa2b6acc6faebae2089b7480af667f5db4528221930a794d0e1f6df8654849f10354ded23b413",
          "sha256": "5da13fedd407c4b649695624446b81856fa97725b928e761d6d6ab9e660fa56a",
          "sha1": "43f9fdff76f26c8dec6169a030168009f04c7654",
          "md5": "875a482a5887b36570eff659b08730f5"
        }
      ]
    }
  ]
}
