{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.2-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.2-Fabric.jar",
          "url": "maple-1.19.2-1.3.2-Fabric.jar",
          "size": 1020579,
          "sha512": "46bd93993efc4e45de47913b50eab7e70f8a38b9c9be1ab6921b22a25a9fb0e0e0a672c34c80464d587eb10997489e3d7d66231d4c90ac534a78c8a8fa9db5b0",
          "sha256": "86c6973b9c2065a22538c820bc213853f6598e94ec36a44e9b92b975f72e8a2f",
          "sha1": "d42f129e39b0c61dc40425ca296d2603d4097ce9",
          "md5": "38ec983cf8de4098e970d7e9a4d98b06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.2-Fabric.jar",
          "url": "maple-1.19.2-1.3.2-Fabric.jar",
          "size": 1020579,
          "sha512": "46bd93993efc4e45de47913b50eab7e70f8a38b9c9be1ab6921b22a25a9fb0e0e0a672c34c80464d587eb10997489e3d7d66231d4c90ac534a78c8a8fa9db5b0",
          "sha256": "86c6973b9c2065a22538c820bc213853f6598e94ec36a44e9b92b975f72e8a2f",
          "sha1": "d42f129e39b0c61dc40425ca296d2603d4097ce9",
          "md5": "38ec983cf8de4098e970d7e9a4d98b06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.2-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.2-Fabric-sources.jar",
          "size": 1070715,
          "sha512": "8c3cf8b1f6d61ed3570346d8760f249f421f79e05ba9ee23fef29a289c0dc4bf17cc17ae71d26b83b0086acf4e5a93f4ebd6c0fbd760b187b86f81a623694c8a",
          "sha256": "0eeae344a22cbaa881fa6c961a68a6557752028dab7a6f6a672849ad43fdc975",
          "sha1": "8622b4e4db022fa7882ee9f664a738f59a6ea852",
          "md5": "83d5ce160a0546b9d5ad36664fda111d"
        }
      ]
    }
  ]
}
