{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "super_apple",
    "version": "3.0.0-pre5-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "super_apple-3.0.0-pre5-1.20.1.jar",
          "url": "super_apple-3.0.0-pre5-1.20.1.jar",
          "size": 324645,
          "sha512": "703b2731c0b2eb205001582d04ea8cc891b13634850c37d0419f26ef6958fb4901786b20c198932444c6f6c2c5f3992f1a00f838c01174179c2b691610b6809f",
          "sha256": "7ee3546189ea32fe59cd75730f093387b803070497e2eb040f1d8b073feb5ddc",
          "sha1": "f0be14a5c73cc7ff815a13bbb30068201df39eae",
          "md5": "be92890c68a070d5267ac2612a8f4d42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "super_apple-3.0.0-pre5-1.20.1.jar",
          "url": "super_apple-3.0.0-pre5-1.20.1.jar",
          "size": 324645,
          "sha512": "703b2731c0b2eb205001582d04ea8cc891b13634850c37d0419f26ef6958fb4901786b20c198932444c6f6c2c5f3992f1a00f838c01174179c2b691610b6809f",
          "sha256": "7ee3546189ea32fe59cd75730f093387b803070497e2eb040f1d8b073feb5ddc",
          "sha1": "f0be14a5c73cc7ff815a13bbb30068201df39eae",
          "md5": "be92890c68a070d5267ac2612a8f4d42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "super_apple-3.0.0-pre5-1.20.1-sources.jar",
          "url": "super_apple-3.0.0-pre5-1.20.1-sources.jar",
          "size": 291230,
          "sha512": "7d71a18a85c0a8601dd22e12266fd6de51063ab6771f3c9aed7af769b7b32a28d99930c50ef736fa0ddf5e2ee91ff7d13e0f7fd419d4579d255a65275a6ebd4a",
          "sha256": "8f3bed5d740e788dae513d1365f0784d9ff173c929700aa6fcfa6028cbf83813",
          "sha1": "72f813f6b7fade3fbf464553051fe03165b91e27",
          "md5": "3c8a0876909f2c976de3196b04e33c84"
        }
      ]
    }
  ]
}
