{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta4-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta4-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta4-Fabric.jar",
          "size": 3431237,
          "sha512": "c727f0034a3565463a0d965819a90635503365b14d67bf04012fea6605eb15154d9d26c1ba95973d0235eb0c709ea005468b91bb2a6b77fd108d720465773f64",
          "sha256": "229716c0a2f62d8a0d04f60142bacc71a61f3d119fa5ffd7e8a67d8d7cb05dde",
          "sha1": "4a203f642840e7ee62fdd15793eaa6e61191516e",
          "md5": "7bedf70dfb1b0ff892f7b66ddef416a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta4-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta4-Fabric.jar",
          "size": 3431237,
          "sha512": "c727f0034a3565463a0d965819a90635503365b14d67bf04012fea6605eb15154d9d26c1ba95973d0235eb0c709ea005468b91bb2a6b77fd108d720465773f64",
          "sha256": "229716c0a2f62d8a0d04f60142bacc71a61f3d119fa5ffd7e8a67d8d7cb05dde",
          "sha1": "4a203f642840e7ee62fdd15793eaa6e61191516e",
          "md5": "7bedf70dfb1b0ff892f7b66ddef416a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta4-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta4-Fabric-sources.jar",
          "size": 954238,
          "sha512": "f4474e196299ebfe6793b165efbfc94fde82ab8285492fa42393605933fbd4940639af89d820fc5992e907886003fab8af2a846727a9b583b6fd1fffff033440",
          "sha256": "ee55741a5ced5c599d9b9b2d3daaf6869572b0b2c7a22422b4f476ec4627a893",
          "sha1": "faf2e198a46a566883b1a8437cbce5de8aa7a25d",
          "md5": "ca37e39772bd5fbc013f184516088be4"
        }
      ]
    }
  ]
}
