{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w04e-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04e-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04e-Fabric.jar",
          "size": 1826051,
          "sha512": "455c9341a133b163fba7848108eeb5c2c96412b47c7734158803883147c49d1cd7bbca47aefe81e543a65863e521a6d309aca6ae3b2cfa449f48dd46af965f02",
          "sha256": "9c562ee7746b792d47205998506d118abb4f3130d8e2cfcb41b2e8c9f0186c1b",
          "sha1": "68967c9cdf712a1f4f6c6ab8e8686bdee50d1596",
          "md5": "17dbc433be7c0465b27d1d99d5426a6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04e-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04e-Fabric.jar",
          "size": 1826051,
          "sha512": "455c9341a133b163fba7848108eeb5c2c96412b47c7734158803883147c49d1cd7bbca47aefe81e543a65863e521a6d309aca6ae3b2cfa449f48dd46af965f02",
          "sha256": "9c562ee7746b792d47205998506d118abb4f3130d8e2cfcb41b2e8c9f0186c1b",
          "sha1": "68967c9cdf712a1f4f6c6ab8e8686bdee50d1596",
          "md5": "17dbc433be7c0465b27d1d99d5426a6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04e-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w04e-Fabric-sources.jar",
          "size": 1826549,
          "sha512": "86253305df249b686c213c8295ba08fa8ba65f628f7fb142ae305b1ff7c7cdcc4d7697cb8a568c1be9d1275918fdaadc12cdd5b2fde503c63e6abac3db4fdd61",
          "sha256": "f2d79907a380793c7d79c3a886a7dba23b8e5c6abd2857990e882e335135f717",
          "sha1": "ac62e248d73ec1ee31a46117e773e9ea04de63e3",
          "md5": "c5c5da4c2a09151dd148812ae0f17f6b"
        }
      ]
    }
  ]
}
