{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta3-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta3-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta3-Fabric.jar",
          "size": 1018352,
          "sha512": "92df73a39d3993a3a6b94640bbfac0c676a3111d1a1b5cd8cffbb550f162a4ad7c4ff207da700f8ad1346b1df8c9c4cdaf34b9e93d7f5fff520edebef9bd8e00",
          "sha256": "2c9b5c49d42bbd9870aed06213358564b3bc98e3a54a2b3289cd4b8bc2fa5b04",
          "sha1": "1c726bc68539d4772844cf1bde2c2a89cfa51a77",
          "md5": "09714760cb0a5a1e3d5785452b64d623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta3-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta3-Fabric.jar",
          "size": 1018352,
          "sha512": "92df73a39d3993a3a6b94640bbfac0c676a3111d1a1b5cd8cffbb550f162a4ad7c4ff207da700f8ad1346b1df8c9c4cdaf34b9e93d7f5fff520edebef9bd8e00",
          "sha256": "2c9b5c49d42bbd9870aed06213358564b3bc98e3a54a2b3289cd4b8bc2fa5b04",
          "sha1": "1c726bc68539d4772844cf1bde2c2a89cfa51a77",
          "md5": "09714760cb0a5a1e3d5785452b64d623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta3-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta3-Fabric-sources.jar",
          "size": 948225,
          "sha512": "49cdbf4a07bb76a5aa6ddcfe219d85bd1ff577dae76053c931eb40cf22c69a9c5c3171139f5fa643e299ae942f1c41e66447b30c625af766c6863db3734e4d29",
          "sha256": "bf1ab6b4cb9a3fb1876194f4d0f8df8097b93c88dde9d8cd3644a318a6150c2f",
          "sha1": "df0b89bbb702bdc5459f821acc513c625c1642b3",
          "md5": "68d5a94387945108f9f4c6800485bb5f"
        }
      ]
    }
  ]
}
