{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "super_apple",
    "version": "2.2.1-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "super_apple-2.2.1-1.20.1.jar",
          "url": "super_apple-2.2.1-1.20.1.jar",
          "size": 154764,
          "sha512": "59c52a5cfcc14ee329a6e90ac65eb54b17bcf0bef451d86ceadcb51d3bc12651dfee5aac46e610a6fc7421ee42b8aea00af471d9e768d54b83baf2fa23095338",
          "sha256": "100870a3e7eb0fb3658133695d6135ce9bbfe467c0199cb7ae4679b2205e14ba",
          "sha1": "31c6389ca3266df6c9a2bf82de73a6537f810787",
          "md5": "5f3b7e22d1ae86be4822d1ad9928af06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "super_apple-2.2.1-1.20.1.jar",
          "url": "super_apple-2.2.1-1.20.1.jar",
          "size": 154764,
          "sha512": "59c52a5cfcc14ee329a6e90ac65eb54b17bcf0bef451d86ceadcb51d3bc12651dfee5aac46e610a6fc7421ee42b8aea00af471d9e768d54b83baf2fa23095338",
          "sha256": "100870a3e7eb0fb3658133695d6135ce9bbfe467c0199cb7ae4679b2205e14ba",
          "sha1": "31c6389ca3266df6c9a2bf82de73a6537f810787",
          "md5": "5f3b7e22d1ae86be4822d1ad9928af06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "super_apple-2.2.1-1.20.1-sources.jar",
          "url": "super_apple-2.2.1-1.20.1-sources.jar",
          "size": 132251,
          "sha512": "3606eefb24ddd615b7d3c79a158d12ab854fac9948cf409e6625e73fdcf641e7dd883153e3b77b91e42c6401342ea0dc408872032372fd5d960768af0843d6a1",
          "sha256": "00aa5e717013b317c959208cb8d1603bcfeb730e0681e13868ddcd7934d4a468",
          "sha1": "ec44c6b39ba6fac64b7dcd05d998f49445d1dca6",
          "md5": "dd6a2064b13355ba56550005fa02600d"
        }
      ]
    }
  ]
}
