{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.105",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.105.jar",
          "url": "alchemy-1.20.1-0.1.105.jar",
          "size": 1567396,
          "sha512": "23fb880bebbb7cdcddf2b30371be33af70b61c76f768df4922b5fb15bcdd781857a1952d8e9dbaad96ac7bba93bbddec92ee5d6f1b23345347fca292f03c29a2",
          "sha256": "5543bc11f43adbddaa08de873daa3995e6676c22bd5fe20f74df5cb81f4cabeb",
          "sha1": "093b0a7d4311a02610d485c65c0e57e82d7aa876",
          "md5": "2ea22546d0b0a4847a0f97487e89d372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.105.jar",
          "url": "alchemy-1.20.1-0.1.105.jar",
          "size": 1567396,
          "sha512": "23fb880bebbb7cdcddf2b30371be33af70b61c76f768df4922b5fb15bcdd781857a1952d8e9dbaad96ac7bba93bbddec92ee5d6f1b23345347fca292f03c29a2",
          "sha256": "5543bc11f43adbddaa08de873daa3995e6676c22bd5fe20f74df5cb81f4cabeb",
          "sha1": "093b0a7d4311a02610d485c65c0e57e82d7aa876",
          "md5": "2ea22546d0b0a4847a0f97487e89d372"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.105-sources.jar",
          "url": "alchemy-1.20.1-0.1.105-sources.jar",
          "size": 1559961,
          "sha512": "51c453184e6b2e4c86e4a4d47f3aa218985facc0a6e94c77516b16598532a7833a91b335da8a24ea0cd320fd8a9b05cece6dfc10be34926cf4a167eef3fa6fd5",
          "sha256": "53d739cfa9390fa0aab1be0bc503c01a3e0a82458ae50a0331bc7a07035655f6",
          "sha1": "ae32c7ce741f8ed5ed7472c43e1da8347574472e",
          "md5": "1c3658cebb40dd4cc3f4f74e9c5b97d4"
        }
      ]
    }
  ]
}
