{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "GrowableOres",
    "version": "1.2.2-1.19.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.2.2-1.19.4.jar",
          "url": "GrowableOres-1.2.2-1.19.4.jar",
          "size": 192249,
          "sha512": "6bcedf294773590db9723d9d416c6a4a5f3f859d658e248237583c53e013ac924491daae13799e6d5d447071703978049d8655429b57cc95a2902f9801acea0b",
          "sha256": "e4e6956b9a175cf44f8c2a7904b5ccfbd666437a0f446ce66fc604a22da37ec2",
          "sha1": "d2b83899219555a2a4fc383680e5132488bd1c35",
          "md5": "9fe1d099980154e7009c1acf4b59a9d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "reborncore-237903",
          "version": {
            "requires": "4443864"
          }
        },
        {
          "group": "curse.maven",
          "module": "techreborn-233564",
          "version": {
            "requires": "4443863"
          }
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.2.2-1.19.4.jar",
          "url": "GrowableOres-1.2.2-1.19.4.jar",
          "size": 192249,
          "sha512": "6bcedf294773590db9723d9d416c6a4a5f3f859d658e248237583c53e013ac924491daae13799e6d5d447071703978049d8655429b57cc95a2902f9801acea0b",
          "sha256": "e4e6956b9a175cf44f8c2a7904b5ccfbd666437a0f446ce66fc604a22da37ec2",
          "sha1": "d2b83899219555a2a4fc383680e5132488bd1c35",
          "md5": "9fe1d099980154e7009c1acf4b59a9d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GrowableOres-1.2.2-1.19.4-sources.jar",
          "url": "GrowableOres-1.2.2-1.19.4-sources.jar",
          "size": 161769,
          "sha512": "f3086cfa2819434e6f294832d1f3e7b82663015c98136e0fe1697f93592b97a70d09733685ab23b872658aa441e91d6cf475450cb2700f9437e43778343d2c0e",
          "sha256": "1a04cfce37a8750733cce24dac7bbffd3fd1fd1ff40ac394c4bc7189f0d3c7ab",
          "sha1": "72330332726316b7fbe628d3ed4abf225b7602ef",
          "md5": "6a1654e905531b77deb7cccee06c7515"
        }
      ]
    }
  ]
}
