{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "GrowableOres",
    "version": "1.3.2-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.2-1.20.1.jar",
          "url": "GrowableOres-1.3.2-1.20.1.jar",
          "size": 223140,
          "sha512": "e3ee954032c9f9ac1af0f0c83c68adff5b5dd6535de7405f44fc56ee2f7b5a9889011a30bbfa7055e1dfe996e268ee609082bb2504a8d780b066f73ebbb434a9",
          "sha256": "95804e540be331b1413d91c0c7aac3299aef92b7241bd01500ee09121a93b94d",
          "sha1": "696e630bbe27fcd7f4e97ff285e7a22f9a6d6292",
          "md5": "6d3a3661e03bfb41c0036ad5cf7c8cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "reborncore-237903",
          "version": {
            "requires": "4582416"
          }
        },
        {
          "group": "curse.maven",
          "module": "techreborn-233564",
          "version": {
            "requires": "4582415"
          }
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.2-1.20.1.jar",
          "url": "GrowableOres-1.3.2-1.20.1.jar",
          "size": 223140,
          "sha512": "e3ee954032c9f9ac1af0f0c83c68adff5b5dd6535de7405f44fc56ee2f7b5a9889011a30bbfa7055e1dfe996e268ee609082bb2504a8d780b066f73ebbb434a9",
          "sha256": "95804e540be331b1413d91c0c7aac3299aef92b7241bd01500ee09121a93b94d",
          "sha1": "696e630bbe27fcd7f4e97ff285e7a22f9a6d6292",
          "md5": "6d3a3661e03bfb41c0036ad5cf7c8cdf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GrowableOres-1.3.2-1.20.1-sources.jar",
          "url": "GrowableOres-1.3.2-1.20.1-sources.jar",
          "size": 191903,
          "sha512": "256cf8ec965f34ff32eda4ae519436dec805138fad087e8347c4e0d67fc8e2b608d56332b64ba3e02f3dc408eb779152cc9bf76de7448b8a0d5149150295b2e5",
          "sha256": "ffa6caa6af072504768c5f7a08174d32126665f21b787326345d27f3af5bcd16",
          "sha1": "373080c1aef2ccb9e0e9da780cc8dfcf76397adf",
          "md5": "76cc0d346b92b68bad12fedfc6ca8a17"
        }
      ]
    }
  ]
}
