{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.9-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.9-Fabric.jar",
          "url": "maple-1.20.1-1.3.9-Fabric.jar",
          "size": 1179592,
          "sha512": "f517213fb24310cf0f647cf6ac1dc992edef1726464571cba914636ad9a2b8fb451870e1d7100ec8257448c82122fcdd779a04f9d8459ac4f0ade4b1c7469760",
          "sha256": "b7567ddd762ed16b2fc5e2a27c559163d91c6681af64bc9c651e096581373d13",
          "sha1": "cc5e7df1425e37a3dc1b832667899bdc00948e82",
          "md5": "35575158f322ecba5ec5c9fc8031f03b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.9-Fabric.jar",
          "url": "maple-1.20.1-1.3.9-Fabric.jar",
          "size": 1179592,
          "sha512": "f517213fb24310cf0f647cf6ac1dc992edef1726464571cba914636ad9a2b8fb451870e1d7100ec8257448c82122fcdd779a04f9d8459ac4f0ade4b1c7469760",
          "sha256": "b7567ddd762ed16b2fc5e2a27c559163d91c6681af64bc9c651e096581373d13",
          "sha1": "cc5e7df1425e37a3dc1b832667899bdc00948e82",
          "md5": "35575158f322ecba5ec5c9fc8031f03b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.9-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.9-Fabric-sources.jar",
          "size": 1116863,
          "sha512": "e9b9052f65e77366e7394a6adc78cf91c13dbf55c90f60576f62c7896af1db5930e4681c87febb4cbae35cfe0d14efff104d8a0527424112e14d333ca66f80fd",
          "sha256": "1569d3398e7bbe112be0b77bceb9e979e86ce0c4a05f1e1465305620f3bbb394",
          "sha1": "d618af33472ba28b1c01f90e0fb3fd3e4f49dc60",
          "md5": "84077ab1e8b55c6a78dfad8522c267b7"
        }
      ]
    }
  ]
}
