{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "super_apple",
    "version": "1.9.0-1.14.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "super_apple-1.9.0-1.14.4.jar",
          "url": "super_apple-1.9.0-1.14.4.jar",
          "size": 90823,
          "sha512": "93135486c48c85964f2f5b1eff16326ad92d64aefca0f6c89669bbd9a44433fd7432c3db4aa575d9fe8d9253bd0fb31e10cd95cfad94d11880ec2d46925e0f46",
          "sha256": "25ba1b277081071c548bd0737efb2538f5a3de4e544343c89a405477770470b6",
          "sha1": "4872f73ff499a8d77cc7cd33b4d5c73471bf1238",
          "md5": "735c6f1d53e359fd241b0613fa32851b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        }
      ],
      "files": [
        {
          "name": "super_apple-1.9.0-1.14.4.jar",
          "url": "super_apple-1.9.0-1.14.4.jar",
          "size": 90823,
          "sha512": "93135486c48c85964f2f5b1eff16326ad92d64aefca0f6c89669bbd9a44433fd7432c3db4aa575d9fe8d9253bd0fb31e10cd95cfad94d11880ec2d46925e0f46",
          "sha256": "25ba1b277081071c548bd0737efb2538f5a3de4e544343c89a405477770470b6",
          "sha1": "4872f73ff499a8d77cc7cd33b4d5c73471bf1238",
          "md5": "735c6f1d53e359fd241b0613fa32851b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "super_apple-1.9.0-1.14.4-sources.jar",
          "url": "super_apple-1.9.0-1.14.4-sources.jar",
          "size": 78324,
          "sha512": "16b01388debf16da2b6f7cc201f149bb56df5a5672083395cca7b3b7b62a12a5eeb5b425641bf7b1aff6ff59c45be2ed47a9b5ae2b2b139c1e36ee7f427fcff0",
          "sha256": "c0e058536a8c9bb58eb393a255382b2f3dc044b3ad94dd6aad1ebc9bcc39f5fe",
          "sha1": "95522bb8436c86aee96e66e9c46d4c8a158654ec",
          "md5": "e48877ffa65a4dde20a6008a238d04bf"
        }
      ]
    }
  ]
}
