{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.12-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.12-Fabric.jar",
          "url": "maple-1.20.1-1.3.12-Fabric.jar",
          "size": 1182692,
          "sha512": "4ac9e0ded6aadf20b380663446b42ea10735bb942006ad8f5c2dc9ebafdae75426f2c814079fd70902a7c04e9fcba99d08687fa64096544d4c214f874e979540",
          "sha256": "cab28fe5d4e31f1aa0c1bf1c719a0c38e25806fc51d17cd9f20dbe906c412189",
          "sha1": "abc74be7beb1800efad7de8332d6c7ec69f9b785",
          "md5": "51c05013cb30750f8ee5f69f7d013120"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.12-Fabric.jar",
          "url": "maple-1.20.1-1.3.12-Fabric.jar",
          "size": 1182692,
          "sha512": "4ac9e0ded6aadf20b380663446b42ea10735bb942006ad8f5c2dc9ebafdae75426f2c814079fd70902a7c04e9fcba99d08687fa64096544d4c214f874e979540",
          "sha256": "cab28fe5d4e31f1aa0c1bf1c719a0c38e25806fc51d17cd9f20dbe906c412189",
          "sha1": "abc74be7beb1800efad7de8332d6c7ec69f9b785",
          "md5": "51c05013cb30750f8ee5f69f7d013120"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.12-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.12-Fabric-sources.jar",
          "size": 1120241,
          "sha512": "d2b08865f9f90b5ccdd0225bed46ae9f176f70b24e52f7ac350bfcee34ed302f91652f6446f30c0f492322ba6fc5d34ba28f408f7be8222f5bdb71cbe5347824",
          "sha256": "edebc4af96cb40c4886469624e152294b2ba3022a9b0a658cf53456748e4edfb",
          "sha1": "bc52a9bb276b463f6efb44a3b8bd83480b1e996b",
          "md5": "dc8cb1035a50d4dd49e08ed0225d40d9"
        }
      ]
    }
  ]
}
