{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.4-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.4-Fabric.jar",
          "url": "maple-1.20.1-1.4.4-Fabric.jar",
          "size": 1834780,
          "sha512": "daef615eaf8d6bcd5d2d0c90c47711844633c1fb73f4cf6868e71971f6e2d1042240da2f2962757eb8b886e456eb753d5785a152b691967221a7ddc9531b7632",
          "sha256": "a0d0ea40008cec8a92bff8556362995e7a37434042c205eb4b085510739bff5d",
          "sha1": "7a7c2cf7e5fc4dc07fa7909b62cfe4484bcdccdc",
          "md5": "042b6ddadcbc5fb0d34c370148341ea9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.4-Fabric.jar",
          "url": "maple-1.20.1-1.4.4-Fabric.jar",
          "size": 1834780,
          "sha512": "daef615eaf8d6bcd5d2d0c90c47711844633c1fb73f4cf6868e71971f6e2d1042240da2f2962757eb8b886e456eb753d5785a152b691967221a7ddc9531b7632",
          "sha256": "a0d0ea40008cec8a92bff8556362995e7a37434042c205eb4b085510739bff5d",
          "sha1": "7a7c2cf7e5fc4dc07fa7909b62cfe4484bcdccdc",
          "md5": "042b6ddadcbc5fb0d34c370148341ea9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.4-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.4-Fabric-sources.jar",
          "size": 1831010,
          "sha512": "add10d0bbc34e4ef4beee4545fa1ad8b2e0139ac01342b041457f910e55bf6897522502a93b09ccd77391ce8b381da9dedd07f169a1ed29b1d2073d0463a327f",
          "sha256": "9e20cd92e720ac4b7ef398e7b2456470958ae533d35daf0f6ef6aa480151d6ad",
          "sha1": "17fbf5db2a5fa0cfc9cf41fa0514059d32619c28",
          "md5": "d11be3261923ff15284366f971100cd6"
        }
      ]
    }
  ]
}
