{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-RC1-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-RC1-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-RC1-Fabric.jar",
          "size": 1176590,
          "sha512": "8641223e3a11a8959380ec01fd840333d39e004f8fffd996385276207651e2f235d9c7b5f675763916b43cdf5887313bb4befab1a8af84773fcca1fbe0a1a1a4",
          "sha256": "8681513dcc43253915f5d468c15d3e41c1f199af653e4c29f77322e09ff4ef88",
          "sha1": "dc2ca4266936ee296c638e79c31b3eb6e40e4d81",
          "md5": "0b764123b11e80e068f4560fb6c5e0cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-RC1-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-RC1-Fabric.jar",
          "size": 1176590,
          "sha512": "8641223e3a11a8959380ec01fd840333d39e004f8fffd996385276207651e2f235d9c7b5f675763916b43cdf5887313bb4befab1a8af84773fcca1fbe0a1a1a4",
          "sha256": "8681513dcc43253915f5d468c15d3e41c1f199af653e4c29f77322e09ff4ef88",
          "sha1": "dc2ca4266936ee296c638e79c31b3eb6e40e4d81",
          "md5": "0b764123b11e80e068f4560fb6c5e0cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-RC1-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-RC1-Fabric-sources.jar",
          "size": 1113985,
          "sha512": "47cea58d08db76f2970b3df278d0c37c35c134ecd19caab5b1491502dcf99173ab0d503b2ed844d49d0b435afd83b7ac9f2d3e8346dda92c011c1ca5610659a8",
          "sha256": "6de7149bcc0bb1f180d454dacd9bcceaeb9fe72ce7fc723948e9bc4d70083feb",
          "sha1": "baf712420be8dbb893b0f97db37cf1bd42a1f7d7",
          "md5": "e3572c961b32ab0f074007b8510e28ed"
        }
      ]
    }
  ]
}
