{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.2-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.2-Fabric.jar",
          "url": "maple-1.20.1-1.3.2-Fabric.jar",
          "size": 1179288,
          "sha512": "01f86e3b05d1f466346c815fa8d409e65634feb8223b2bbe7a8b268b1986521425b830f13c42a2bed2b704752d7383af72430376655071a7d8ead8619c1254fd",
          "sha256": "b7ddec7782bce0ca27043fdcb1de57a5f561ee435c7be723cfa8d38958e40ad7",
          "sha1": "34521c550478d515af1dff5dd6cb226abab5b8ec",
          "md5": "c03641dea0f744d7bedb8469f2cdac88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.2-Fabric.jar",
          "url": "maple-1.20.1-1.3.2-Fabric.jar",
          "size": 1179288,
          "sha512": "01f86e3b05d1f466346c815fa8d409e65634feb8223b2bbe7a8b268b1986521425b830f13c42a2bed2b704752d7383af72430376655071a7d8ead8619c1254fd",
          "sha256": "b7ddec7782bce0ca27043fdcb1de57a5f561ee435c7be723cfa8d38958e40ad7",
          "sha1": "34521c550478d515af1dff5dd6cb226abab5b8ec",
          "md5": "c03641dea0f744d7bedb8469f2cdac88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.2-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.2-Fabric-sources.jar",
          "size": 1116722,
          "sha512": "420392878cb8e69cb485356441302a48b0ca51dd5cb84cad4437f537ec2f73e9ff7701742c4554c53689e97510961eeed1dfa37e6382194fd3812b78b87e3e7a",
          "sha256": "368a14b181de49834f8301cd1e7ea283a1dac050d849d70d76deafb15e14379f",
          "sha1": "ff4103c7a295f6710cd3d4bec8760e69a551f245",
          "md5": "022d5823192b4ba4327db1a6eaa5bdf7"
        }
      ]
    }
  ]
}
