{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.5-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.5-Fabric.jar",
          "url": "maple-1.20.1-1.3.5-Fabric.jar",
          "size": 1179510,
          "sha512": "b0e26a6cc0b51905334eab1bef828e70cc938c79c9271a45078969a05c245382027effe05c3cd44e1523de2db32f1ed053a5227fdde294c0fa0fb2a62dbfff30",
          "sha256": "391f1cab2fb837451ec11bc24e84f3188b6e9c86f0513fb873da84fea767ed21",
          "sha1": "7a91804621be40ce12b186e17b34a39e5c0a3071",
          "md5": "2d5aee506029c520ab4cc47b4ea9555e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.5-Fabric.jar",
          "url": "maple-1.20.1-1.3.5-Fabric.jar",
          "size": 1179510,
          "sha512": "b0e26a6cc0b51905334eab1bef828e70cc938c79c9271a45078969a05c245382027effe05c3cd44e1523de2db32f1ed053a5227fdde294c0fa0fb2a62dbfff30",
          "sha256": "391f1cab2fb837451ec11bc24e84f3188b6e9c86f0513fb873da84fea767ed21",
          "sha1": "7a91804621be40ce12b186e17b34a39e5c0a3071",
          "md5": "2d5aee506029c520ab4cc47b4ea9555e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.5-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.5-Fabric-sources.jar",
          "size": 1116795,
          "sha512": "043d3eb8f93ff4887353324e19e45fb8ad722b062239a429a82e793409cf901c89bd2ece461be1eada19847020791fb5fcf07c46e8c04226e0a294222e4904e4",
          "sha256": "4eaebc670a14fee9d456962f2a801ec49900fe5740bba360c0733e860f418812",
          "sha1": "30af30d3fae05fcbc61536b0416842476fbb1a8a",
          "md5": "1f0fc20bd055d04ec2a5c766e05fe1f7"
        }
      ]
    }
  ]
}
