{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.4-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.4-Fabric.jar",
          "url": "maple-1.19.2-1.3.4-Fabric.jar",
          "size": 1020588,
          "sha512": "f5dbcb5cb58299964fbbb5ed3d5a11af0692994d89ae7f4a018397f6023b2e2115e87c6e42b741ea05f0403af9b54a056bca89838c8efe39d9ed49b201f9ec18",
          "sha256": "90a00ba448a953282477f343311244196e38e39489501ca81cf82582a8a231f7",
          "sha1": "c320d172339a13001c874dcd2977ca53947014f8",
          "md5": "6a48226b66ac121bce9df4ac9cc8587d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.4-Fabric.jar",
          "url": "maple-1.19.2-1.3.4-Fabric.jar",
          "size": 1020588,
          "sha512": "f5dbcb5cb58299964fbbb5ed3d5a11af0692994d89ae7f4a018397f6023b2e2115e87c6e42b741ea05f0403af9b54a056bca89838c8efe39d9ed49b201f9ec18",
          "sha256": "90a00ba448a953282477f343311244196e38e39489501ca81cf82582a8a231f7",
          "sha1": "c320d172339a13001c874dcd2977ca53947014f8",
          "md5": "6a48226b66ac121bce9df4ac9cc8587d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.4-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.4-Fabric-sources.jar",
          "size": 1070721,
          "sha512": "fcffa9a979c2d95efa4c2b4b2bec5d8d698bee6a3bb6a2697090b2e9ff97824f1084f532702a56271be93b7c68e95144f69df9dfc6e0b69ecc18ba6c15ec5057",
          "sha256": "08c642a97bf9be3d7b77601eba96883b3a24efdb24c80a7216302e7a65aab7d7",
          "sha1": "16f72b6d13b7d0c08b2f7fe96c03b43f6db71ad2",
          "md5": "ed5993d829f36d443d06ae34910b3d51"
        }
      ]
    }
  ]
}
