{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "super_apple",
    "version": "2.0.10-1.19.4-rc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "super_apple-2.0.10-1.19.4-rc2.jar",
          "url": "super_apple-2.0.10-1.19.4-rc2.jar",
          "size": 96978,
          "sha512": "c8dea91ab09845423511df37f0c8a4edc3ec9be5795acbf5d6cad78ae59e6617a23f52dbc7ed91bd5362242b854b3795616dee748493aadc8a3152c560a7de7f",
          "sha256": "f7f604547fb80012853b366602f26bd6a549b37aed38b997d9018263826b4fe5",
          "sha1": "1dccfc0083cecdb70643609e1a71489fe833ba03",
          "md5": "791f1e58376de98060756afbadb6d62b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.75.3+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "super_apple-2.0.10-1.19.4-rc2.jar",
          "url": "super_apple-2.0.10-1.19.4-rc2.jar",
          "size": 96978,
          "sha512": "c8dea91ab09845423511df37f0c8a4edc3ec9be5795acbf5d6cad78ae59e6617a23f52dbc7ed91bd5362242b854b3795616dee748493aadc8a3152c560a7de7f",
          "sha256": "f7f604547fb80012853b366602f26bd6a549b37aed38b997d9018263826b4fe5",
          "sha1": "1dccfc0083cecdb70643609e1a71489fe833ba03",
          "md5": "791f1e58376de98060756afbadb6d62b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "super_apple-2.0.10-1.19.4-rc2-sources.jar",
          "url": "super_apple-2.0.10-1.19.4-rc2-sources.jar",
          "size": 83157,
          "sha512": "eabfe083676c1f882449a6f6418d5cc79364446c08b6ebb228e13cc0f7571ccd126f8e9c62654d840fcf265f36a4961b8b4949527dd42547550dc601740c2a56",
          "sha256": "040fc8518c72a67a017569674714f83c6620de2ea0111b9972ef881d37cf1189",
          "sha1": "8a2e55ca9adaae3ef9a065b524450c5d17a2bdf7",
          "md5": "0310f92af922a0cff87ec1e759d9e8dd"
        }
      ]
    }
  ]
}
