{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta16-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta16-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta16-Fabric.jar",
          "size": 1176592,
          "sha512": "d8bdb8d180289a3026c7fa14332afd9d87ece42038f631929febee2d9cc1ce4f301571de7185ae949f6188f68eac1a71659dd0a16557c7beb867d0e473a50408",
          "sha256": "72c265df394f4565e07b6b0f13608aee556a941d78aeae6a0cffb0497483cd41",
          "sha1": "21797a1367101866fdfceb811738635cef4a695b",
          "md5": "00697543f9fa4649625e9ec1c4e94d1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta16-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta16-Fabric.jar",
          "size": 1176592,
          "sha512": "d8bdb8d180289a3026c7fa14332afd9d87ece42038f631929febee2d9cc1ce4f301571de7185ae949f6188f68eac1a71659dd0a16557c7beb867d0e473a50408",
          "sha256": "72c265df394f4565e07b6b0f13608aee556a941d78aeae6a0cffb0497483cd41",
          "sha1": "21797a1367101866fdfceb811738635cef4a695b",
          "md5": "00697543f9fa4649625e9ec1c4e94d1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta16-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta16-Fabric-sources.jar",
          "size": 1113985,
          "sha512": "353d3cd6c337c908c300461e2c9400709c3cd40c8541ec3376ae3dd977f233fe99eeadaed894aee8eab91d583e6f8613090b008852a7660c87af3eaf4b4085e4",
          "sha256": "59b0f232b759528ad3dc7cf3ad924adf23a928aeedae794e3074150c4bbbbf07",
          "sha1": "7a57fda8db50d31dcb6527e06cec005d1f897752",
          "md5": "2267bacbc9eebf7f8d58710c1230abe5"
        }
      ]
    }
  ]
}
