{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.0-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.0-Fabric.jar",
          "url": "maple-1.19.2-1.3.0-Fabric.jar",
          "size": 1020524,
          "sha512": "f28a4d7ebb16ae1f7d0b4259813219343d67530093be54bd37b857cff3a2a1e991a3634540a6f510d9d440ec7ff66435f11bb1ae5db91d59758378a4e19a54a5",
          "sha256": "f44500095f261b439969957885eb9b560145827f63cdd298438e1e6d2c1fcdb0",
          "sha1": "de4ec036bfa325ebbd504eef6c969565947cb948",
          "md5": "a098d245b61b7f40c74205ecfd6f3ec0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.0-Fabric.jar",
          "url": "maple-1.19.2-1.3.0-Fabric.jar",
          "size": 1020524,
          "sha512": "f28a4d7ebb16ae1f7d0b4259813219343d67530093be54bd37b857cff3a2a1e991a3634540a6f510d9d440ec7ff66435f11bb1ae5db91d59758378a4e19a54a5",
          "sha256": "f44500095f261b439969957885eb9b560145827f63cdd298438e1e6d2c1fcdb0",
          "sha1": "de4ec036bfa325ebbd504eef6c969565947cb948",
          "md5": "a098d245b61b7f40c74205ecfd6f3ec0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.0-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.0-Fabric-sources.jar",
          "size": 1070689,
          "sha512": "76f98f8a4d8ad1ac5110783ee898f61ab5c7032900199161b3a17cdb3afe10f70090405840b0c3f84f21fac7e26e03bfa1ae8af13d11dd0ba0188e53794ae65b",
          "sha256": "e46113eff2621f1ceff34ebc93515667c3b4c3de953bb409fefd33517ad7b93d",
          "sha1": "a486ba4ccfe73568ac611546a81c393f4acd172a",
          "md5": "b4838084ced7406e35092879cd6281b2"
        }
      ]
    }
  ]
}
