{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta2-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta2-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta2-Fabric.jar",
          "size": 1013645,
          "sha512": "7207aa006016499c599b9fe8e8cbe307fb88afa75a3a71527f300c363e49a8be1d1361cae096b1fff9fb747c8953122732e38b49ae04e1623f6e46736c479730",
          "sha256": "cf2ab3dd173b1741bad69622e2a5d731090376febdf2a5366301462308a7a253",
          "sha1": "14c28ced5654b76da026fca86c72d9b6ad9848cf",
          "md5": "030a7b5690df99266bcfb33e3d51cf07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta2-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta2-Fabric.jar",
          "size": 1013645,
          "sha512": "7207aa006016499c599b9fe8e8cbe307fb88afa75a3a71527f300c363e49a8be1d1361cae096b1fff9fb747c8953122732e38b49ae04e1623f6e46736c479730",
          "sha256": "cf2ab3dd173b1741bad69622e2a5d731090376febdf2a5366301462308a7a253",
          "sha1": "14c28ced5654b76da026fca86c72d9b6ad9848cf",
          "md5": "030a7b5690df99266bcfb33e3d51cf07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta2-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta2-Fabric-sources.jar",
          "size": 944525,
          "sha512": "524bcbafe450b23569b7fc5adb2f3d0a8eaf71bcfb0b2bd71d4d0076d05bb87135647c329116a7aa7be6d9d9b39e2cf7509b3c1c0bae3c04817aae741153c3bf",
          "sha256": "a8261f7809ae7fdc6f1c49e130252bc084c3327bf47470a24fbe9d049abeb0dc",
          "sha1": "65d8c87ceccb8595bb18057b1e87e5735cc09849",
          "md5": "2b381836b7dc73ead96efe54460bad8d"
        }
      ]
    }
  ]
}
