{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.137",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.137.jar",
          "url": "alchemy-1.20.1-0.1.137.jar",
          "size": 1693731,
          "sha512": "17d7d06f9e16d6814c879525cf757d96b2f7b020369dcb3b6a6f1aba0bf2742d0160a808a2f22e7792ef9b77459ff802fbcbefbe654e161e2ecea25f2904af4f",
          "sha256": "0f21b66a3e6a9bc26d3496b1b122b10c26390124624240a252f83d8aeaa597a2",
          "sha1": "2659901dff393eeab2c2a21d1d9d0e1d6a9470e1",
          "md5": "d9264008e249d4a6896b8aa23e0084c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.137.jar",
          "url": "alchemy-1.20.1-0.1.137.jar",
          "size": 1693731,
          "sha512": "17d7d06f9e16d6814c879525cf757d96b2f7b020369dcb3b6a6f1aba0bf2742d0160a808a2f22e7792ef9b77459ff802fbcbefbe654e161e2ecea25f2904af4f",
          "sha256": "0f21b66a3e6a9bc26d3496b1b122b10c26390124624240a252f83d8aeaa597a2",
          "sha1": "2659901dff393eeab2c2a21d1d9d0e1d6a9470e1",
          "md5": "d9264008e249d4a6896b8aa23e0084c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.137-sources.jar",
          "url": "alchemy-1.20.1-0.1.137-sources.jar",
          "size": 1681086,
          "sha512": "342839cf211f6415c07592f53ba28a4e5d85f809988da052ff1e630242771dd39e37048c4eeeb6bef4bc27e84b244a0bdb7a7727812e582b0b947f1d64218600",
          "sha256": "59f890693a73c148325bda86860e3bb204e00f1de287c12401d4b7c682e0bb7a",
          "sha1": "e54f0fde05028609d02c3dee9585e49320ff1021",
          "md5": "215a65fba137fa0e5dda47120075f6fb"
        }
      ]
    }
  ]
}
