{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta8-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta8-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta8-Fabric.jar",
          "size": 1114459,
          "sha512": "7618f1c2e60bd4a5755f25bb8167fe0cb066e32b13d72e8dcd066ebb3faf60e162d662e93e7129823b6b28cfdc3a3458d177470884cff2d3ae4a4c9b3ec8b252",
          "sha256": "a96838a35345cc1420d5e549f2bd83b809aee746e3fa1cf151d7a87ac97334c7",
          "sha1": "0607643e07af65d7de7a0095b2c49ffe2d4f8832",
          "md5": "4adb232fb7e47e2d2648b0201f5f5692"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta8-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta8-Fabric.jar",
          "size": 1114459,
          "sha512": "7618f1c2e60bd4a5755f25bb8167fe0cb066e32b13d72e8dcd066ebb3faf60e162d662e93e7129823b6b28cfdc3a3458d177470884cff2d3ae4a4c9b3ec8b252",
          "sha256": "a96838a35345cc1420d5e549f2bd83b809aee746e3fa1cf151d7a87ac97334c7",
          "sha1": "0607643e07af65d7de7a0095b2c49ffe2d4f8832",
          "md5": "4adb232fb7e47e2d2648b0201f5f5692"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta8-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta8-Fabric-sources.jar",
          "size": 1046567,
          "sha512": "45d39731bf2de84f702d0d58ba1b507b08bc3cb2f90a4b542904090053b6f57a0c616928be40dd590998035637822d710c087b998f5068e1b2c383bc3fbeb617",
          "sha256": "2ccb37836351ba2bd7b03cf4ff7c0c9573432cd31390398c91c78b93f5ea7a04",
          "sha1": "9d79014f76b542fb790b2960782985513c596f99",
          "md5": "29d070c641d91f108e9958b8c93fe5c6"
        }
      ]
    }
  ]
}
