{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.13-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.13-Fabric.jar",
          "url": "maple-1.20.1-1.4.13-Fabric.jar",
          "size": 1993512,
          "sha512": "c9505cad3038522d57550b937e412a060e60189d81fe07b3a4224aa109798e6f022c18cefd548f6c619b511d4fc820175e4aa80f3a0efb54a205104cc2da8dca",
          "sha256": "834f266a10d2bc382e8b0ce456bbd40b09129db797a4cccb52bfb5465b4088bd",
          "sha1": "c4621e0c073b9806c00ceb84580642db4e19f914",
          "md5": "8be27c7b71faa99314c4195cc3457139"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.13-Fabric.jar",
          "url": "maple-1.20.1-1.4.13-Fabric.jar",
          "size": 1993512,
          "sha512": "c9505cad3038522d57550b937e412a060e60189d81fe07b3a4224aa109798e6f022c18cefd548f6c619b511d4fc820175e4aa80f3a0efb54a205104cc2da8dca",
          "sha256": "834f266a10d2bc382e8b0ce456bbd40b09129db797a4cccb52bfb5465b4088bd",
          "sha1": "c4621e0c073b9806c00ceb84580642db4e19f914",
          "md5": "8be27c7b71faa99314c4195cc3457139"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.13-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.13-Fabric-sources.jar",
          "size": 2006185,
          "sha512": "0a45fab7d6f6330ebf7f04f0fa6c7085e402b99f1ed2b73043886d9441824c329ea1bb1a4a4be41fa3d097d1dcabf18bf37852b3482b79ee9ea636be2cb8d876",
          "sha256": "c323023fd4e71de9b7436ae36e716aa877e8d476087d85ad8236297695189223",
          "sha1": "a8cb9389d96725120d3cf2f4fe378e4b3ccc497b",
          "md5": "b82f2dce19b3dc9094423f35ebdd81cb"
        }
      ]
    }
  ]
}
