{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w04b-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04b-Fabric.jar",
          "size": 1621402,
          "sha512": "0299d1b7ebe3eb9161691926311ffcd8f97f2fe63c92806d29b352430f278d13f57a29707c0e9d6eee6f8ef421c1231a2b460278cf290129c79c5791a0d8d469",
          "sha256": "cc3f6e1177bc4b01ae12003cd1f70c4d801bf5b6d02927af966db8e4a0c2a50d",
          "sha1": "38c76cacdf0fe5a46c82de9a50cc3c89fd6e23d7",
          "md5": "e674ef68fb14eb9933ab60873aa6b775"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04b-Fabric.jar",
          "size": 1621402,
          "sha512": "0299d1b7ebe3eb9161691926311ffcd8f97f2fe63c92806d29b352430f278d13f57a29707c0e9d6eee6f8ef421c1231a2b460278cf290129c79c5791a0d8d469",
          "sha256": "cc3f6e1177bc4b01ae12003cd1f70c4d801bf5b6d02927af966db8e4a0c2a50d",
          "sha1": "38c76cacdf0fe5a46c82de9a50cc3c89fd6e23d7",
          "md5": "e674ef68fb14eb9933ab60873aa6b775"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04b-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w04b-Fabric-sources.jar",
          "size": 1609209,
          "sha512": "cf7b2403b7cf478c144429786e147e3cd721c743531ccc062b5de056c7a31132e0fd63cfd4d9cc59469573a717bb00a2d7920229c397c022979e7d0a1145ccb1",
          "sha256": "257b26ef48b1f75e5a6cbefb4daaa340d76e27992c390f777eb23bcc322c0ede",
          "sha1": "b911b5af85ec054b50b12c92b7f004e421c4218d",
          "md5": "bb5bbd6995f0b5f7f245e16057f458a5"
        }
      ]
    }
  ]
}
