{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.1-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.1-Fabric.jar",
          "url": "maple-1.19.2-1.3.1-Fabric.jar",
          "size": 1020525,
          "sha512": "22b6646bfbe4e10ddcbbaa8464c241c3a2fa660d86b360eb16d0eb8819bbcb9840ce0c3087c7c3fd36cedc410c1d8ca260d64ae90ff789a2e335ee054c67a3c0",
          "sha256": "5118ff728a3961270ff95caa6ac249bf355bf714cf76732ea61b4394db6e0ce3",
          "sha1": "369bf6f2ce3780e33ddfcdf5db49a757bf2b23cc",
          "md5": "710625abc54cec108f2169716fd78311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.1-Fabric.jar",
          "url": "maple-1.19.2-1.3.1-Fabric.jar",
          "size": 1020525,
          "sha512": "22b6646bfbe4e10ddcbbaa8464c241c3a2fa660d86b360eb16d0eb8819bbcb9840ce0c3087c7c3fd36cedc410c1d8ca260d64ae90ff789a2e335ee054c67a3c0",
          "sha256": "5118ff728a3961270ff95caa6ac249bf355bf714cf76732ea61b4394db6e0ce3",
          "sha1": "369bf6f2ce3780e33ddfcdf5db49a757bf2b23cc",
          "md5": "710625abc54cec108f2169716fd78311"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.1-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.1-Fabric-sources.jar",
          "size": 1070691,
          "sha512": "1b23c6ecf66e8900bf8927e34bbc9eef564f0b668ac104c310cd0a832d895e3444fde180d9d980662b39dff3d9102148c9eba10c018bc8229f46f34e2f5765c9",
          "sha256": "ca3332e33b75edfb6024b0305839c21f5c7455f758a56d20ebd26ca78276c460",
          "sha1": "208e907a3989072e868790f722aa68fa25506b72",
          "md5": "2f7495486cdfabbd13e19f1583af5454"
        }
      ]
    }
  ]
}
