{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.1.0-Beta3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.1.0-Beta3.jar",
          "url": "maple-1.19.2-1.1.0-Beta3.jar",
          "size": 582181,
          "sha512": "ca8ee351dda686671cd13b350dd3c5ba5e0d16b5d95050898bf74ad0fc5c22fe9d63261ba9f0da05e51116f26a8873b5dcb455067e30609e504aea8321d6c3b1",
          "sha256": "2babd7c534c7e51a4789b8bd16fa4f18a6c44007f5e00e8b66eb9b39414e8250",
          "sha1": "7ede89cc18a0925080c0e7708a40f25279a8db40",
          "md5": "db045f2787939990923640edeeafe132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.136"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.1.0-Beta3.jar",
          "url": "maple-1.19.2-1.1.0-Beta3.jar",
          "size": 582181,
          "sha512": "ca8ee351dda686671cd13b350dd3c5ba5e0d16b5d95050898bf74ad0fc5c22fe9d63261ba9f0da05e51116f26a8873b5dcb455067e30609e504aea8321d6c3b1",
          "sha256": "2babd7c534c7e51a4789b8bd16fa4f18a6c44007f5e00e8b66eb9b39414e8250",
          "sha1": "7ede89cc18a0925080c0e7708a40f25279a8db40",
          "md5": "db045f2787939990923640edeeafe132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.1.0-Beta3-sources.jar",
          "url": "maple-1.19.2-1.1.0-Beta3-sources.jar",
          "size": 592609,
          "sha512": "a940164a2ab905a332dfdce7d79bb1c309c701859b362efe88d3d1885258e744e0d5530d311c37e85e6f4db36463c5a5b72ce88905a85da18106bfeb67b64906",
          "sha256": "85ef6e9cfcefe5fee924678351b5adfa599929cffe96f64e4ef7eb3c835677c6",
          "sha1": "32343e431816eddd98dc12a0407b67a5c15b812f",
          "md5": "7017f16d0b414bdff4c96f7af85afb40"
        }
      ]
    }
  ]
}
