{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.11-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.11-Fabric.jar",
          "url": "maple-1.20.1-1.3.11-Fabric.jar",
          "size": 1182354,
          "sha512": "5f638355ac5c8cac63cebf2e895bddd796bec81379d66ca21ffe2afa5955ded2a0a2082220b9afbf8c98ac67fd27ed3c97959493189ed27ea91a3a3419c04b6b",
          "sha256": "994410085116384c608516b24e937d4ea7e5ca512e23428865556fde65d83e7a",
          "sha1": "e2da7ce11340c157abf9747350439dbce1818fa8",
          "md5": "5dc4bccc95211524179c3a71b0a3bf33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.11-Fabric.jar",
          "url": "maple-1.20.1-1.3.11-Fabric.jar",
          "size": 1182354,
          "sha512": "5f638355ac5c8cac63cebf2e895bddd796bec81379d66ca21ffe2afa5955ded2a0a2082220b9afbf8c98ac67fd27ed3c97959493189ed27ea91a3a3419c04b6b",
          "sha256": "994410085116384c608516b24e937d4ea7e5ca512e23428865556fde65d83e7a",
          "sha1": "e2da7ce11340c157abf9747350439dbce1818fa8",
          "md5": "5dc4bccc95211524179c3a71b0a3bf33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.11-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.11-Fabric-sources.jar",
          "size": 1119785,
          "sha512": "97036934b890ae91633fbe7549920e993c64a419d1fba7f2d24cc71a982d5ce644a13cdf15394c046651f3c81b3a9d465b4009b17cf8ebbf82bf02a01610ff77",
          "sha256": "705d2979d0932334c74a5f87cd5f5c04ee4969a63545fcc22458731cda8c8bda",
          "sha1": "606bf9bc497739fff53d29f0376115aaec1ca724",
          "md5": "28b2403c68ed2a793ac65df72a4e2f42"
        }
      ]
    }
  ]
}
