{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta6-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta6-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta6-Fabric.jar",
          "size": 1065221,
          "sha512": "72119c83e426212e6d5abe0a0ec5dd8e64ad1e99bfae86c874a916e2ed728bf880da6834ce8ac65322bfa645ca3e1152058e10e61f938744df9b59a245f1e2bf",
          "sha256": "54d8a482de5c07e8d58840964d6090b85d067fc77a6058a326e92c0bf34db87a",
          "sha1": "4b37a09fc4c8ee96754718d5c932eb78f9f01e4b",
          "md5": "cb87a47b4557bf4ffed7bc8f3f4ced00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta6-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta6-Fabric.jar",
          "size": 1065221,
          "sha512": "72119c83e426212e6d5abe0a0ec5dd8e64ad1e99bfae86c874a916e2ed728bf880da6834ce8ac65322bfa645ca3e1152058e10e61f938744df9b59a245f1e2bf",
          "sha256": "54d8a482de5c07e8d58840964d6090b85d067fc77a6058a326e92c0bf34db87a",
          "sha1": "4b37a09fc4c8ee96754718d5c932eb78f9f01e4b",
          "md5": "cb87a47b4557bf4ffed7bc8f3f4ced00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta6-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta6-Fabric-sources.jar",
          "size": 999190,
          "sha512": "888c93eef0e81fd4659fbce984c2308be30c0447bcfe434681df98748e12f7b7d2481c9e23cbc24d46a428b3d45ea3b71f7887e67c8678c5c5c8b4cccc3b439a",
          "sha256": "7d0018dc5736cfacb3fa7286ca25c6d05a92b4a46c9b03581b6acec13959d501",
          "sha1": "80da255def37f965614d9c1e16d83eef7ce9b47b",
          "md5": "d4fe9da8fa5c88b967ab4df2c773cbb7"
        }
      ]
    }
  ]
}
