{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.11-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.11-Fabric.jar",
          "url": "maple-1.19.2-1.3.11-Fabric.jar",
          "size": 1022704,
          "sha512": "e05673778fd61664431f04888747859d77f184026b12c6f03c02bf7388d52603393199a2b41cb80bf10cc787c6be5cc8f7cb21a3a39d8a62001308ba7eec9d23",
          "sha256": "1561e9d0a3e3b744125f337935e3da2a8397f91be259dd9b6e81a23e1e707955",
          "sha1": "1312aa90d0a327977e163d46e4f632db5550a80c",
          "md5": "b584458cbd819109d3981264df5267f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.11-Fabric.jar",
          "url": "maple-1.19.2-1.3.11-Fabric.jar",
          "size": 1022704,
          "sha512": "e05673778fd61664431f04888747859d77f184026b12c6f03c02bf7388d52603393199a2b41cb80bf10cc787c6be5cc8f7cb21a3a39d8a62001308ba7eec9d23",
          "sha256": "1561e9d0a3e3b744125f337935e3da2a8397f91be259dd9b6e81a23e1e707955",
          "sha1": "1312aa90d0a327977e163d46e4f632db5550a80c",
          "md5": "b584458cbd819109d3981264df5267f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.11-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.11-Fabric-sources.jar",
          "size": 1072839,
          "sha512": "336cb573598e3e92a9e825499de1d6809287e84c0bbdaee6f813178c9a50b5a25b2d288ee680cec33eba72f6ed34b70b7012471a41ce928e896c57ba4cc6c3c8",
          "sha256": "65f52fe2820bf5f29c9e8238ac45839b8ac4acb7924bbb38b66af991c26fd1fb",
          "sha1": "9cb7eca8db3399d375d5bfdf773acf468cf44932",
          "md5": "10e4791fd3344b8cb29d0c26700005a0"
        }
      ]
    }
  ]
}
