{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w03b-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w03b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w03b-Fabric.jar",
          "size": 1612744,
          "sha512": "a665989a45f81b3dcc0daebefb6eecc0050686c8aa77c62b13aecbe8781fb7387629b480ffe0b9ecf01ab0e80a6574e2612be4d2e4781d2e4e27133eb9282bb9",
          "sha256": "a94148213c440b09974cd17f59427eb0912274c19fb8225301aff95dcb353e0c",
          "sha1": "8309779aa6d5c2f52ed7e8a37603030843ef7816",
          "md5": "352e2ce9bb3a69e776df898cd11560a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w03b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w03b-Fabric.jar",
          "size": 1612744,
          "sha512": "a665989a45f81b3dcc0daebefb6eecc0050686c8aa77c62b13aecbe8781fb7387629b480ffe0b9ecf01ab0e80a6574e2612be4d2e4781d2e4e27133eb9282bb9",
          "sha256": "a94148213c440b09974cd17f59427eb0912274c19fb8225301aff95dcb353e0c",
          "sha1": "8309779aa6d5c2f52ed7e8a37603030843ef7816",
          "md5": "352e2ce9bb3a69e776df898cd11560a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w03b-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w03b-Fabric-sources.jar",
          "size": 1600433,
          "sha512": "5020db315a64bd5f8257bbb4d8b8bd3720ed1994b6e2e00e4e453aba4c1843dd70b10e6ca763c299386a209cc4ec079e3c3eaa4131fc9e6debf08623a6affe06",
          "sha256": "04d55128952093c7a87401cfd8634927fa53129ebe1a06b9c0497b8accde7846",
          "sha1": "9c6470217ec5dfd2cdf090bfd01c13e8d158b09b",
          "md5": "b0e1d1e215f1c6fb30d482f4a14b0e10"
        }
      ]
    }
  ]
}
