{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.107",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.107.jar",
          "url": "alchemy-1.20.1-0.1.107.jar",
          "size": 1573811,
          "sha512": "0a7ba7ebb1f1d02e7c9ca4f3a4a6a8e752c08c44f32e7a175ab4ad44956c338543ed71319b9c6349ebfa21f2db4d92b04b59cec28fef0540e8aad38bec310ed6",
          "sha256": "e7fbe0dd6b07a24b4847e38c926cdc7cfbb001d10cff385229185c39658565b4",
          "sha1": "12ab9a8d02641431e92fd77067dc80b3a86ddb46",
          "md5": "5cfcd2f2dbcd048c743df31e819defb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.107.jar",
          "url": "alchemy-1.20.1-0.1.107.jar",
          "size": 1573811,
          "sha512": "0a7ba7ebb1f1d02e7c9ca4f3a4a6a8e752c08c44f32e7a175ab4ad44956c338543ed71319b9c6349ebfa21f2db4d92b04b59cec28fef0540e8aad38bec310ed6",
          "sha256": "e7fbe0dd6b07a24b4847e38c926cdc7cfbb001d10cff385229185c39658565b4",
          "sha1": "12ab9a8d02641431e92fd77067dc80b3a86ddb46",
          "md5": "5cfcd2f2dbcd048c743df31e819defb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.107-sources.jar",
          "url": "alchemy-1.20.1-0.1.107-sources.jar",
          "size": 1563083,
          "sha512": "26edaeb750f3dd4daf595cbe8cecbccebbca00828d836c44448d14900d2022e2e259af45c6bf833ed3682d365ad8d80e30607f68cdaef7f9543e193b6b7470be",
          "sha256": "f1aabb5371d1749419696b2ab2c18bbad186920bb59607aef5ce3a7ab40defc3",
          "sha1": "7bc23a8a6f777fa582d502d7694dcde5ac92abbd",
          "md5": "c3b78e628287bdeb36138957daa78184"
        }
      ]
    }
  ]
}
