{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta13-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta13-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta13-Fabric.jar",
          "size": 1158524,
          "sha512": "c071efdc2cbb19ca1b982a3c2fd37026b6e29a4448e31fe9bd396eff41c6f1715555715e11aa06524b4496556cd6b9774dce48ffb5f8de3437b9cdaece912f93",
          "sha256": "8a6562363f6557eb59001fc0c40c68e5a10e57b5fa6e4868dbe3b543c0b2a172",
          "sha1": "786b3b2347f6c4282fa9b7848aa9289bd42b4d2b",
          "md5": "1160f3428337cde93d0f4d6192c0e058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta13-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta13-Fabric.jar",
          "size": 1158524,
          "sha512": "c071efdc2cbb19ca1b982a3c2fd37026b6e29a4448e31fe9bd396eff41c6f1715555715e11aa06524b4496556cd6b9774dce48ffb5f8de3437b9cdaece912f93",
          "sha256": "8a6562363f6557eb59001fc0c40c68e5a10e57b5fa6e4868dbe3b543c0b2a172",
          "sha1": "786b3b2347f6c4282fa9b7848aa9289bd42b4d2b",
          "md5": "1160f3428337cde93d0f4d6192c0e058"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta13-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta13-Fabric-sources.jar",
          "size": 1094376,
          "sha512": "fc96acd71c362400550189129700f9b06fc5676df1c32d57ee7b9a4120b001ce426ae06e358ead2677b4c002d89cdac55812c2a988e2b6a459b73705b37f43fc",
          "sha256": "a63592640457f0831d8f96505b4deb26ae719c7bd1c3656ed46f81c56571e8a6",
          "sha1": "12f524c447cbe3e98a6dbe6c2f2e038f65e320a4",
          "md5": "104786aee6f93f7be76ec385f139b4c7"
        }
      ]
    }
  ]
}
