{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta5-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta5-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta5-Fabric.jar",
          "size": 1026153,
          "sha512": "e1ed164f70f52db67a0c24aadebbc562850c65a859ced064cc2e781505e0f51413089be8e6b45fd7812cb19f4ed5c32ed1780851f52e6639ed9c62139e61eb6f",
          "sha256": "0016a2ccf3a5fd843aa02278948f0387ae2d09f48687752a872a608877fb11b7",
          "sha1": "d95da8867af8c99a41b2532b9d7f6a24195a82dd",
          "md5": "a6f4e6036b1386f899a0d47343b6ab66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta5-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta5-Fabric.jar",
          "size": 1026153,
          "sha512": "e1ed164f70f52db67a0c24aadebbc562850c65a859ced064cc2e781505e0f51413089be8e6b45fd7812cb19f4ed5c32ed1780851f52e6639ed9c62139e61eb6f",
          "sha256": "0016a2ccf3a5fd843aa02278948f0387ae2d09f48687752a872a608877fb11b7",
          "sha1": "d95da8867af8c99a41b2532b9d7f6a24195a82dd",
          "md5": "a6f4e6036b1386f899a0d47343b6ab66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta5-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta5-Fabric-sources.jar",
          "size": 956341,
          "sha512": "e28792a7e7308216956699be4da41e1c070f858df6d677bd0703b88c3b9011913b03749a5fb6ce84c0ca0375fe5189da03836786561a77823cc60240c59ac6c2",
          "sha256": "5ee17ca2d665a633b2747559ccca7e2bd64a8f264fe147a5287a0cb255cd3606",
          "sha1": "2aa58e740b07cb006827c227b25076d6f542692b",
          "md5": "493a68cb50a27b1b7c08bfa7ee015126"
        }
      ]
    }
  ]
}
