{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.134",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.134.jar",
          "url": "alchemy-1.20.1-0.1.134.jar",
          "size": 1693129,
          "sha512": "a6c2de25b2c96900487f4559fdb6ea24df887cfdfe782713b7b57c52fb4c7caf2860d3f8c712f9cbb6cfcd384c135116016d2d538187cc7d7c44320f0b582b3b",
          "sha256": "ea1340c73741a5a859dea5a93cdba5beff22a3365dbdfc23f0b4c1ec38f3ecb0",
          "sha1": "4272212c7feed175793c1ac91b440be4c0532ae1",
          "md5": "0ce7ccebef772d1a1378f70ae89ac888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.134.jar",
          "url": "alchemy-1.20.1-0.1.134.jar",
          "size": 1693129,
          "sha512": "a6c2de25b2c96900487f4559fdb6ea24df887cfdfe782713b7b57c52fb4c7caf2860d3f8c712f9cbb6cfcd384c135116016d2d538187cc7d7c44320f0b582b3b",
          "sha256": "ea1340c73741a5a859dea5a93cdba5beff22a3365dbdfc23f0b4c1ec38f3ecb0",
          "sha1": "4272212c7feed175793c1ac91b440be4c0532ae1",
          "md5": "0ce7ccebef772d1a1378f70ae89ac888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.134-sources.jar",
          "url": "alchemy-1.20.1-0.1.134-sources.jar",
          "size": 1680973,
          "sha512": "7505c8478834fd8f6dd4096f083da158eedcf7004c4f33229e26260d9e983624b1b75016991c1ce66241ef0bd524c8c3818d33a380b5f9e40b48b236fc72404d",
          "sha256": "d28082e303e01f451b5dd493b77f0993f26ec954d8c221fbc314e9f1441402e1",
          "sha1": "47b5b3649c3bbffc33275361e61f0d26eaabe5ee",
          "md5": "2abb1288473bc6ba129dc2e205f18068"
        }
      ]
    }
  ]
}
