{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.13-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.13-Fabric.jar",
          "url": "maple-1.20.1-1.3.13-Fabric.jar",
          "size": 1182680,
          "sha512": "b61c91a1d49e26ec5571dcfa186bfb55dcfea53cfc7bbe12f869956a3e52d5344da7e23e64abd00e6af43f044217ee37d9ef83c5aa73ff4ab5d8a84ba73348be",
          "sha256": "b95c3695a118ae30ab386f39e7c1709791031ca0a9233a8b6b58c568aac5a749",
          "sha1": "2a73b3f41151d6836a2adca70e2389550c734b81",
          "md5": "350d20dfdf436b40ba316da9e843be8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.13-Fabric.jar",
          "url": "maple-1.20.1-1.3.13-Fabric.jar",
          "size": 1182680,
          "sha512": "b61c91a1d49e26ec5571dcfa186bfb55dcfea53cfc7bbe12f869956a3e52d5344da7e23e64abd00e6af43f044217ee37d9ef83c5aa73ff4ab5d8a84ba73348be",
          "sha256": "b95c3695a118ae30ab386f39e7c1709791031ca0a9233a8b6b58c568aac5a749",
          "sha1": "2a73b3f41151d6836a2adca70e2389550c734b81",
          "md5": "350d20dfdf436b40ba316da9e843be8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.13-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.13-Fabric-sources.jar",
          "size": 1120244,
          "sha512": "02f4959003d157273a462a80a45a8b28755feedcb1d47c30a12b96e2782112deac43b3c97eb29d923f14650bbd7a88f44237564f48cb73df493d4458d792c584",
          "sha256": "4629baa46131dd8e221d7bd513ffc68bcbe3bd9ce6974681b7f6b31fde01c9c4",
          "sha1": "b9e6d170759e2ed38c76b4c070adc6900db01939",
          "md5": "ab9be6c7b14c6e514ee38184fff3205b"
        }
      ]
    }
  ]
}
