{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "GrowableOres",
    "version": "1.3.6-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.6-1.20.1.jar",
          "url": "GrowableOres-1.3.6-1.20.1.jar",
          "size": 228723,
          "sha512": "a420a664b489577cbed2f340a016051bbdb8b200223b83b791a30a96418c8efcded51f39a0241757033ff45541e9b4e603f81af12a9da775032692e8293ca694",
          "sha256": "f2a94b6b83ac9e26d995e3a7e890928afff28c85daf0715b0c83e509e0591d37",
          "sha1": "af648e61e2d600ab37d2682a8a91d4be5b2b1eca",
          "md5": "c14831f6880df2629e133ad30458eab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "reborncore-237903",
          "version": {
            "requires": "4582416"
          }
        },
        {
          "group": "curse.maven",
          "module": "techreborn-233564",
          "version": {
            "requires": "4582415"
          }
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.6-1.20.1.jar",
          "url": "GrowableOres-1.3.6-1.20.1.jar",
          "size": 228723,
          "sha512": "a420a664b489577cbed2f340a016051bbdb8b200223b83b791a30a96418c8efcded51f39a0241757033ff45541e9b4e603f81af12a9da775032692e8293ca694",
          "sha256": "f2a94b6b83ac9e26d995e3a7e890928afff28c85daf0715b0c83e509e0591d37",
          "sha1": "af648e61e2d600ab37d2682a8a91d4be5b2b1eca",
          "md5": "c14831f6880df2629e133ad30458eab4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GrowableOres-1.3.6-1.20.1-sources.jar",
          "url": "GrowableOres-1.3.6-1.20.1-sources.jar",
          "size": 197405,
          "sha512": "a16fc1a14a231a738d4e68e3311c2a56797196bef06f5261f4c4a92ac15d3976b8a0102d9585c0e3edae0386b2dd8c6ff6bafb92cdbefd3972c6e54e284e89c7",
          "sha256": "88ac06f48e065830711bff69b0aa88a6b20133c3418f541b879886199e29fdad",
          "sha1": "f7f1b5d35c122ff651ed1ef10dbe294a1e71aa17",
          "md5": "f0f437d0fc1b9b560f333477224be66b"
        }
      ]
    }
  ]
}
