{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.7-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.7-Fabric.jar",
          "url": "maple-1.19.2-1.3.7-Fabric.jar",
          "size": 1021935,
          "sha512": "b20a9ec8a4233d208cf2d1a12086a3062d6ea37a8f10936a80354c594954cad35ee4d43e31802394a967a193f244734bf6aae217d3984870f49127be13c41359",
          "sha256": "9c782704c4b99b08539b1e649bf9bceaf3cf48a428fe889cde588629759d52af",
          "sha1": "c16395095e00a803695d03bffa31cf615518d100",
          "md5": "5ec958e8d4f0fdbcaeaa257a9258843a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.7-Fabric.jar",
          "url": "maple-1.19.2-1.3.7-Fabric.jar",
          "size": 1021935,
          "sha512": "b20a9ec8a4233d208cf2d1a12086a3062d6ea37a8f10936a80354c594954cad35ee4d43e31802394a967a193f244734bf6aae217d3984870f49127be13c41359",
          "sha256": "9c782704c4b99b08539b1e649bf9bceaf3cf48a428fe889cde588629759d52af",
          "sha1": "c16395095e00a803695d03bffa31cf615518d100",
          "md5": "5ec958e8d4f0fdbcaeaa257a9258843a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.7-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.7-Fabric-sources.jar",
          "size": 1071926,
          "sha512": "6968fe027bf8f450cbad16c571b69a97f9e6e9c2704b738760bc3e984fef72ff8036d752bb3ae82faac0d35c0a3d3089c7774e84a90b9000c0d8c0330596e496",
          "sha256": "73f21789c5de6a9e302048ff7068d4802397da721253a9cefd45a2e8546ba905",
          "sha1": "7a7c87703d5242b2527fc26ff1f921fae43fa511",
          "md5": "34441e8063fcffb58749169765b5c9b9"
        }
      ]
    }
  ]
}
