{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.5-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.5-Fabric.jar",
          "url": "maple-1.20.1-1.4.5-Fabric.jar",
          "size": 1834757,
          "sha512": "313a5353dd34462f1cf34fcd8f4b18f5ea73f5e8cc2b021d21651e67d312454f75a10170d704efd25021724fcada46ed95c632087b28e52c208601b45087d5c5",
          "sha256": "0ff6989dc31cea6989c608c6dc3dab3824b051b917b072ec6101f73a48136b8a",
          "sha1": "ec0962f503046ecf756bb2127e39adf1499ffb94",
          "md5": "301fbf132edcf6c074c3c39cc81a1cb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.5-Fabric.jar",
          "url": "maple-1.20.1-1.4.5-Fabric.jar",
          "size": 1834757,
          "sha512": "313a5353dd34462f1cf34fcd8f4b18f5ea73f5e8cc2b021d21651e67d312454f75a10170d704efd25021724fcada46ed95c632087b28e52c208601b45087d5c5",
          "sha256": "0ff6989dc31cea6989c608c6dc3dab3824b051b917b072ec6101f73a48136b8a",
          "sha1": "ec0962f503046ecf756bb2127e39adf1499ffb94",
          "md5": "301fbf132edcf6c074c3c39cc81a1cb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.5-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.5-Fabric-sources.jar",
          "size": 1830986,
          "sha512": "d9ead120c10189511e8b9d6ed7aab36c96585a22285df84419a198d6e055be0772ba055d32eec0b4b4eb535f7054cd8fb4f049a95641a479f0a392e41c07eabc",
          "sha256": "43aed2c1ee11d8bf99e268082260037e35d7f6509b2da9fc3aa79b20cd726fa3",
          "sha1": "02d09af5629aac328f3dc4e1a313a81ffed5ea87",
          "md5": "9a3634e584e454ac658655f6844817d9"
        }
      ]
    }
  ]
}
