{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.8-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.8-Fabric.jar",
          "url": "maple-1.20.1-1.3.8-Fabric.jar",
          "size": 1179592,
          "sha512": "c169cc3c65556148939adcae58958f7111916438526cabdd4b4c21404995e1fd0323be706d10d2f1ff1a02ed43afcabaac3c3f1a04e8ed263719e0276136af17",
          "sha256": "570e8e70d9292b1580e874abb1911a41a34466c94ff8c9a9b0b50189fcc393c7",
          "sha1": "49dac13cd3ca32b8ba615d3b164ed4d7a19bb252",
          "md5": "70b6595b62ce2323cd1b614a30577995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.8-Fabric.jar",
          "url": "maple-1.20.1-1.3.8-Fabric.jar",
          "size": 1179592,
          "sha512": "c169cc3c65556148939adcae58958f7111916438526cabdd4b4c21404995e1fd0323be706d10d2f1ff1a02ed43afcabaac3c3f1a04e8ed263719e0276136af17",
          "sha256": "570e8e70d9292b1580e874abb1911a41a34466c94ff8c9a9b0b50189fcc393c7",
          "sha1": "49dac13cd3ca32b8ba615d3b164ed4d7a19bb252",
          "md5": "70b6595b62ce2323cd1b614a30577995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.8-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.8-Fabric-sources.jar",
          "size": 1116857,
          "sha512": "269ea1ca85acf80c2404a77a4875c42bdae23ae672b28b795fa5b75e5acfd94be32c4ff840c7de450602a9a28021094bc68b4deca355c0302ae969133236e000",
          "sha256": "a5caa098c5ea733fade1df6f35da1eae56335e5780ccb421d5ca32102c8c5fbd",
          "sha1": "1f17a195eb6bf21c1350ab0f432f7f1138d285e0",
          "md5": "8fa1fcdcafa32255603ef10d3b4df157"
        }
      ]
    }
  ]
}
