{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.14-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.14-Fabric.jar",
          "url": "maple-1.20.1-1.4.14-Fabric.jar",
          "size": 1993552,
          "sha512": "9ab57e2c67b146e77eb56cbdfcff8ff47f54ee8fd9dc613e56f42a1b24db62be05bc84fa9a5521bb955faa3c7331d0d14fb0b5f53c79898a9cc70c7ec94672d6",
          "sha256": "0137359ef10cd83f1d976ca845f41dda7ac3c33ebe1d2aff96fd9e32bc3e80dd",
          "sha1": "6a4f0428f74f0345f27a9ae4d448097564ef3adb",
          "md5": "fdcf8e4f3a076eeea8ce6244841ced3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.14-Fabric.jar",
          "url": "maple-1.20.1-1.4.14-Fabric.jar",
          "size": 1993552,
          "sha512": "9ab57e2c67b146e77eb56cbdfcff8ff47f54ee8fd9dc613e56f42a1b24db62be05bc84fa9a5521bb955faa3c7331d0d14fb0b5f53c79898a9cc70c7ec94672d6",
          "sha256": "0137359ef10cd83f1d976ca845f41dda7ac3c33ebe1d2aff96fd9e32bc3e80dd",
          "sha1": "6a4f0428f74f0345f27a9ae4d448097564ef3adb",
          "md5": "fdcf8e4f3a076eeea8ce6244841ced3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.14-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.14-Fabric-sources.jar",
          "size": 2006225,
          "sha512": "c91098388fdb76bc142089fa5b1d2dce195cd3b3fbabd353caea7e52ba20799a2892e60e4d025212c4c723fe90eb66fb98d868559c770ad2e098181a3275ff62",
          "sha256": "ac73eef8608d504f493ee6f770010d133203c072c706d659497b19ac23a9d8ed",
          "sha1": "5226cfaaa05dffacd06634c0eae7409ea35cc95f",
          "md5": "7a3d2048d95277136c7ba60d8a239315"
        }
      ]
    }
  ]
}
