{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.11-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.11-Fabric.jar",
          "url": "maple-1.20.1-1.4.11-Fabric.jar",
          "size": 1993137,
          "sha512": "682ef4871e74876bb78cc62f8494be32b77e5a8848ba6d7f1a8c43f8f6ba5b20e2595fc9a2cfce428aebf83a6d90ec1e6583b823c0822d3188e5d957de0fa825",
          "sha256": "fb68316a06ceb7bfd52705005953c4b2b6a9042f69159ba045a8702c659c4c1c",
          "sha1": "7a03e77b39232933ca24c0b1e4608234dbcbd39b",
          "md5": "e628363a03b9bc7de1db1d8723232cc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.11-Fabric.jar",
          "url": "maple-1.20.1-1.4.11-Fabric.jar",
          "size": 1993137,
          "sha512": "682ef4871e74876bb78cc62f8494be32b77e5a8848ba6d7f1a8c43f8f6ba5b20e2595fc9a2cfce428aebf83a6d90ec1e6583b823c0822d3188e5d957de0fa825",
          "sha256": "fb68316a06ceb7bfd52705005953c4b2b6a9042f69159ba045a8702c659c4c1c",
          "sha1": "7a03e77b39232933ca24c0b1e4608234dbcbd39b",
          "md5": "e628363a03b9bc7de1db1d8723232cc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.11-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.11-Fabric-sources.jar",
          "size": 2005975,
          "sha512": "ac02b32773aa10f25b20e032c4ddff2b0c21efd3d4bc0591c8a039a0585a87b522f3ea6a4892a4ec820480799ab45c788ae4b6ad6d1c50673ff3b3c2f9f23b3d",
          "sha256": "a4e836db7af46c07fe779278f8f4157d89bf6d688aab4708c76681d0eee80f40",
          "sha1": "95b79fc8cd917020c9f294ea01135c1dcd0d2741",
          "md5": "3371a8e7cf2d45ef57f79f9b507b2251"
        }
      ]
    }
  ]
}
