{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.133",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.133.jar",
          "url": "alchemy-1.20.1-0.1.133.jar",
          "size": 1693096,
          "sha512": "e79b022880e86d3458b31291d49a36fdc9d10ad539feadb32a3924d66f7c7ad4c44cad29273cd672bd4a387602c747688b5b9017f5ead1c88598aa012ec164d5",
          "sha256": "e9bd962f0583c676b4575f2f96ce9755ed13aed97e6846904389ccc66096ca10",
          "sha1": "c79fbcd7c939db27f5ff81815f8164d473b9f8a1",
          "md5": "fd8aa672a359b13263907de85674c79a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.133.jar",
          "url": "alchemy-1.20.1-0.1.133.jar",
          "size": 1693096,
          "sha512": "e79b022880e86d3458b31291d49a36fdc9d10ad539feadb32a3924d66f7c7ad4c44cad29273cd672bd4a387602c747688b5b9017f5ead1c88598aa012ec164d5",
          "sha256": "e9bd962f0583c676b4575f2f96ce9755ed13aed97e6846904389ccc66096ca10",
          "sha1": "c79fbcd7c939db27f5ff81815f8164d473b9f8a1",
          "md5": "fd8aa672a359b13263907de85674c79a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.133-sources.jar",
          "url": "alchemy-1.20.1-0.1.133-sources.jar",
          "size": 1680962,
          "sha512": "53ee4684451b2983f54fc8acfb55e56eaef02fe14f6dd7645655a5ee0373052b017d9e5e49753ebb0b8af252e1243f8d4a35c6d21776be912b441abf3a534dd0",
          "sha256": "79ed1602e514c74178289d37480720a37a641bbb124b479aea8e368995c3bb9d",
          "sha1": "6c4fe5596830c966aa92fe47d4ed5efe93594ccf",
          "md5": "07cb0978f578ecc23576175c456ebfcd"
        }
      ]
    }
  ]
}
