{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.1.0-Alpha2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.1.0-Alpha2.jar",
          "url": "maple-1.20.1-1.1.0-Alpha2.jar",
          "size": 843949,
          "sha512": "e4694de3a6204550f852e91e8dc99e4b630176f70a3780d652aa8f6732d2296c7f2c4a8b14f764d83d4b81562c05f6b727477b872cd67d54bb43c6c25e828b60",
          "sha256": "2bf5db6f98380d9dbb840c9f79b772a5c92e3d88d34e18d1f2228865eb75281b",
          "sha1": "588e2e7e261721fa2523118aa33dd0b43e288c7d",
          "md5": "a31e0439571755d41a84e48f0a968fed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.86.0+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.1.0-Alpha2.jar",
          "url": "maple-1.20.1-1.1.0-Alpha2.jar",
          "size": 843949,
          "sha512": "e4694de3a6204550f852e91e8dc99e4b630176f70a3780d652aa8f6732d2296c7f2c4a8b14f764d83d4b81562c05f6b727477b872cd67d54bb43c6c25e828b60",
          "sha256": "2bf5db6f98380d9dbb840c9f79b772a5c92e3d88d34e18d1f2228865eb75281b",
          "sha1": "588e2e7e261721fa2523118aa33dd0b43e288c7d",
          "md5": "a31e0439571755d41a84e48f0a968fed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.1.0-Alpha2-sources.jar",
          "url": "maple-1.20.1-1.1.0-Alpha2-sources.jar",
          "size": 687719,
          "sha512": "dfdfb34a0e4638e3c2c5562ec70256984282e72dc97c3fc7d65dbe2170abebe2a60ee0218b601d9ca61ac264cc3d6232b24a292229c349653716e7c21b986e0b",
          "sha256": "f1af013fe7271a6f28146274b44c9d541f2f8b5ebb6c8d550d1d9a376ee90057",
          "sha1": "733ef01ee442aa3eda1d9034b43e92b67a7d41ba",
          "md5": "9ffe0eb48e846396572a217e5a646972"
        }
      ]
    }
  ]
}
