{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta14-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta14-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta14-Fabric.jar",
          "size": 1175080,
          "sha512": "cf3e935f3a93005f3c85ce4ea4f51ac6e03a85e6d1b6d4b703993ffceeb4a9eaabf032b425bf750257419639f3160cef16036ebb26d70dea872ead8054bb9523",
          "sha256": "a8002a47402f8ee923d6491c0abff0f20abbff2c542548375f23dd3e410e128b",
          "sha1": "94c558277d4ec94d677ba3f030e5e03ec583e1cb",
          "md5": "b0acd6a0afab39dca1306c0e34e29f6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta14-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta14-Fabric.jar",
          "size": 1175080,
          "sha512": "cf3e935f3a93005f3c85ce4ea4f51ac6e03a85e6d1b6d4b703993ffceeb4a9eaabf032b425bf750257419639f3160cef16036ebb26d70dea872ead8054bb9523",
          "sha256": "a8002a47402f8ee923d6491c0abff0f20abbff2c542548375f23dd3e410e128b",
          "sha1": "94c558277d4ec94d677ba3f030e5e03ec583e1cb",
          "md5": "b0acd6a0afab39dca1306c0e34e29f6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta14-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta14-Fabric-sources.jar",
          "size": 1111943,
          "sha512": "ebe4d7e2ebade59f77c1e3dfbb7c8f8e1ebf8fa3487ae7eb7ee5731f629b091d1813e8a40c27169828beaff41555b90fd2077044f3de4b0c5d88e483bd103809",
          "sha256": "3ab3dcac489f423ffc9f49af5c7e607d0bbc2d885ddfc3e4c61277ea7639aae3",
          "sha1": "4f5caa1707ddb209335cb6d5d91c55dfd8ca8a50",
          "md5": "583eaa152a5bce51473003b33d33476a"
        }
      ]
    }
  ]
}
