{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.106",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.106.jar",
          "url": "alchemy-1.20.1-0.1.106.jar",
          "size": 1571723,
          "sha512": "903b718533bc3fbf883a6ca54736cbf1728bc9abff2a98038798b80975af57dd2ebcc6320bf044821cb632501c2c83b5caf40504beb8749691c8752aa29633ed",
          "sha256": "88060c5b8d6ae81ad0fe984115a36e996166f096dd6ebdbec77195ec413816ff",
          "sha1": "fe4a6fbe05d2601480e67f823e8d04db0b485dd2",
          "md5": "13b97b068073a07ab21f436054614e98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.106.jar",
          "url": "alchemy-1.20.1-0.1.106.jar",
          "size": 1571723,
          "sha512": "903b718533bc3fbf883a6ca54736cbf1728bc9abff2a98038798b80975af57dd2ebcc6320bf044821cb632501c2c83b5caf40504beb8749691c8752aa29633ed",
          "sha256": "88060c5b8d6ae81ad0fe984115a36e996166f096dd6ebdbec77195ec413816ff",
          "sha1": "fe4a6fbe05d2601480e67f823e8d04db0b485dd2",
          "md5": "13b97b068073a07ab21f436054614e98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.106-sources.jar",
          "url": "alchemy-1.20.1-0.1.106-sources.jar",
          "size": 1561864,
          "sha512": "ab732177ca508469a1c8b7cb95b06c51218c1c09d56f5b2a598d4f67e8707680efd4ae6da6a9ccf50775ff7fd202525250b26c56bfaff6a0a77fb566e0fda767",
          "sha256": "506d06552f07d8974ae3fbb66b1092f883b6bb48ba4e6a81c37dad3568be3d9a",
          "sha1": "e5949a45d0fcbac787a99d3364fbd5c204ffed26",
          "md5": "9fe7d2a53135e71cfb8aaa2760e44bcf"
        }
      ]
    }
  ]
}
