{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w04d-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04d-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04d-Fabric.jar",
          "size": 1623617,
          "sha512": "c8e6f20609fdac6ca8d8f3efda7599983010c24f056ad2f44618d26f857a83b72931f52464eb394ef5f4040a493b8bb8d36377a1e6fef588b5ac85de824f726b",
          "sha256": "abeb64a1af6ce8dfa0e1de5cda76845120f5b29133f2f171c2f3b8832d4620fe",
          "sha1": "87e89333666d01e31f163c912eec6dbbb957d7d4",
          "md5": "3ca4565af6a4972df00e9abc09e3fbb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04d-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04d-Fabric.jar",
          "size": 1623617,
          "sha512": "c8e6f20609fdac6ca8d8f3efda7599983010c24f056ad2f44618d26f857a83b72931f52464eb394ef5f4040a493b8bb8d36377a1e6fef588b5ac85de824f726b",
          "sha256": "abeb64a1af6ce8dfa0e1de5cda76845120f5b29133f2f171c2f3b8832d4620fe",
          "sha1": "87e89333666d01e31f163c912eec6dbbb957d7d4",
          "md5": "3ca4565af6a4972df00e9abc09e3fbb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04d-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w04d-Fabric-sources.jar",
          "size": 1611353,
          "sha512": "6c7d9fb2528d4e49ece4c380f130256f972cc04d2d82bd62ce7676bcbed4d42e2789845ee180cdafde965ffef8bee16f66ff53afccbcfc5613ca60d4fe344d5f",
          "sha256": "d4445f79787cc3dc6a1f5dfb96cbc2562822f8059f2de8a2eb3cd406bc013ded",
          "sha1": "eaa2e2940c74b2c0f16c2fbaf85bcbb317493599",
          "md5": "8d8362a37a023879581c362627836dab"
        }
      ]
    }
  ]
}
