{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.111",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.111.jar",
          "url": "alchemy-1.20.1-0.1.111.jar",
          "size": 1654019,
          "sha512": "8bd8d8e8ac4af5110726916e63edf5591fd3e1dc9aa2ba8102cb348e05bae9e89d3a30a41ba368f55b627188a44ff459124aac99d8ec92da82a0e855d93787c2",
          "sha256": "f809592ef8bb426d796b338342ebc52576de54c02155f95d4835652f048331d9",
          "sha1": "b63aec27d7ca08054bac1a4cd70418f7af608b9d",
          "md5": "e87e80f5d58eb57a9a88373fbd283b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.111.jar",
          "url": "alchemy-1.20.1-0.1.111.jar",
          "size": 1654019,
          "sha512": "8bd8d8e8ac4af5110726916e63edf5591fd3e1dc9aa2ba8102cb348e05bae9e89d3a30a41ba368f55b627188a44ff459124aac99d8ec92da82a0e855d93787c2",
          "sha256": "f809592ef8bb426d796b338342ebc52576de54c02155f95d4835652f048331d9",
          "sha1": "b63aec27d7ca08054bac1a4cd70418f7af608b9d",
          "md5": "e87e80f5d58eb57a9a88373fbd283b8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.111-sources.jar",
          "url": "alchemy-1.20.1-0.1.111-sources.jar",
          "size": 1646394,
          "sha512": "7e7a7afc48e7944c57df16da111eb1e0cad1f33ab8b7a8fa7589a7a251a4384f5895cc837b241152f5a0fd8df1c64d8fc81c28f194eb20b73dd28d3b4776869a",
          "sha256": "5eef3748b961053d34d819040c34e6af7b045e071b3504d566d47809606e7ce2",
          "sha1": "93cdef90681d8d9ba47f267fc43164df3390b9ae",
          "md5": "9a31170c20c5df976ea524ba254a6b81"
        }
      ]
    }
  ]
}
