{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Fabric.jar",
          "size": 1176585,
          "sha512": "1d1ea67603a20d66371d1ec7c497246f3a52a9e809879a21e9eba26e1b07376cad4fc5a07960c7cca53130994ee70749393441f4f19ffb44666478e5ccc68a74",
          "sha256": "75e6c0602a3896c61092ed78f20b50e93388414a37eac7ce15b034c7abfeb2d7",
          "sha1": "66a8a2aa7918c0f8fb9a29cfdf76a70a201f3180",
          "md5": "eef3868cd0343285e325937a711e180b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Fabric.jar",
          "size": 1176585,
          "sha512": "1d1ea67603a20d66371d1ec7c497246f3a52a9e809879a21e9eba26e1b07376cad4fc5a07960c7cca53130994ee70749393441f4f19ffb44666478e5ccc68a74",
          "sha256": "75e6c0602a3896c61092ed78f20b50e93388414a37eac7ce15b034c7abfeb2d7",
          "sha1": "66a8a2aa7918c0f8fb9a29cfdf76a70a201f3180",
          "md5": "eef3868cd0343285e325937a711e180b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Fabric-sources.jar",
          "size": 1113985,
          "sha512": "18e8140b4ea6eedfce7195335096d7b6617eabee9270a986bd9121bd7fa4b2e704ccce5f02e4c0164f1b78b864a97b558d5c473f36c3afede5bacf643a964555",
          "sha256": "7b4400cba2d07b9ad68b6d4b6c5049c12bd601d70acaad26878f4f1d6d4c4cd5",
          "sha1": "09fe1a8e42c801d03c3328be0777739fc046d4f3",
          "md5": "e6bbe6990fdb9b7788924f2d4048cc1b"
        }
      ]
    }
  ]
}
