{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.110",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.110.jar",
          "url": "alchemy-1.20.1-0.1.110.jar",
          "size": 1653693,
          "sha512": "5f86227de39e990105484ca5fc68ba44d4c438dc75d26afe2bd3c63142bc97d12e2e2b46943203412c133ecc7a5298fa42a61ef4776670811406177f9494779a",
          "sha256": "9ef7e360d52f798b84f55469ebebefa13bfe03ddde1a6e8bc98540cec8136ef8",
          "sha1": "1fb456011dd940ce6a6824335e813c1ceae6398c",
          "md5": "b3de527bef8851f1161d691b3942c21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.110.jar",
          "url": "alchemy-1.20.1-0.1.110.jar",
          "size": 1653693,
          "sha512": "5f86227de39e990105484ca5fc68ba44d4c438dc75d26afe2bd3c63142bc97d12e2e2b46943203412c133ecc7a5298fa42a61ef4776670811406177f9494779a",
          "sha256": "9ef7e360d52f798b84f55469ebebefa13bfe03ddde1a6e8bc98540cec8136ef8",
          "sha1": "1fb456011dd940ce6a6824335e813c1ceae6398c",
          "md5": "b3de527bef8851f1161d691b3942c21d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.110-sources.jar",
          "url": "alchemy-1.20.1-0.1.110-sources.jar",
          "size": 1646394,
          "sha512": "2bef84351e0ab559daa3e6274f92e1a92534734d25394efef5e100daca3cc76647cb893d40a23c240aaa87c67ac495cf9c59c0f69a04cb708c8481e0c9fb7387",
          "sha256": "f94e7b9652e1b57de35020e7517be3af049b03b3920d3bc520d2c33c4a9ad869",
          "sha1": "97989e11901dd771263ca3811a176640c3a87f37",
          "md5": "886ab3a0286e0e873c3b80d8e53bf409"
        }
      ]
    }
  ]
}
