{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "GrowableOres",
    "version": "1.3.0-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.0-1.20.1.jar",
          "url": "GrowableOres-1.3.0-1.20.1.jar",
          "size": 206731,
          "sha512": "6983a9ad7deb5f9dd02d42ddeb8d4fb61ef94a7d4ebc6680eb3257325214ab476675e08747f416c0f74f5b2b75f6d408b9e67e97f68d3206f289ac6a29ab7603",
          "sha256": "576403c790b5552c8ccc1e774f1052d6541d1429dde18cec52e0e083892054c4",
          "sha1": "dc4261cd7de1ca72a5b13b9435c4397f35d47476",
          "md5": "cef5667b46aead948b819509c0a6292e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "reborncore-237903",
          "version": {
            "requires": "4582416"
          }
        },
        {
          "group": "curse.maven",
          "module": "techreborn-233564",
          "version": {
            "requires": "4582415"
          }
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.0-1.20.1.jar",
          "url": "GrowableOres-1.3.0-1.20.1.jar",
          "size": 206731,
          "sha512": "6983a9ad7deb5f9dd02d42ddeb8d4fb61ef94a7d4ebc6680eb3257325214ab476675e08747f416c0f74f5b2b75f6d408b9e67e97f68d3206f289ac6a29ab7603",
          "sha256": "576403c790b5552c8ccc1e774f1052d6541d1429dde18cec52e0e083892054c4",
          "sha1": "dc4261cd7de1ca72a5b13b9435c4397f35d47476",
          "md5": "cef5667b46aead948b819509c0a6292e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GrowableOres-1.3.0-1.20.1-sources.jar",
          "url": "GrowableOres-1.3.0-1.20.1-sources.jar",
          "size": 175564,
          "sha512": "2bdc8a74d72d9950fc75113b9273e3195b57a3dbbe88d77622b8646b9e387924a555a450727e5e5ded16eace8f3f3413248e2ea7ef160e8ca5b8a90b4cd2549a",
          "sha256": "8dd555bdd00135414817f5c8b5836d9b7a1fe49ea4fe231565f14969bbf1d531",
          "sha1": "1ddb3d812e894622d031b1bdbc55bbd6c838e0bb",
          "md5": "11b40a4b978484cba700e4f057020ef9"
        }
      ]
    }
  ]
}
