{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.131",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.131.jar",
          "url": "alchemy-1.20.1-0.1.131.jar",
          "size": 1692641,
          "sha512": "50c6cea28ca636d8d63f68c8605473012cdaa2238dc3b646111e233600a6e03155b602f2195ac9ace93e7988b5205f48baf597b9db8ecdf2b4b7ac03e717185e",
          "sha256": "cacd0a6c116a30e29ff13e3788b09a8999688250991f5277c4598b3b77c0abe9",
          "sha1": "23e66eeb14cd0dd16d3a68229ad60bd1a383a4ae",
          "md5": "22a21fe75603bee2eb80a2c0d37b747e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.131.jar",
          "url": "alchemy-1.20.1-0.1.131.jar",
          "size": 1692641,
          "sha512": "50c6cea28ca636d8d63f68c8605473012cdaa2238dc3b646111e233600a6e03155b602f2195ac9ace93e7988b5205f48baf597b9db8ecdf2b4b7ac03e717185e",
          "sha256": "cacd0a6c116a30e29ff13e3788b09a8999688250991f5277c4598b3b77c0abe9",
          "sha1": "23e66eeb14cd0dd16d3a68229ad60bd1a383a4ae",
          "md5": "22a21fe75603bee2eb80a2c0d37b747e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.131-sources.jar",
          "url": "alchemy-1.20.1-0.1.131-sources.jar",
          "size": 1680801,
          "sha512": "a5864f62bda5c37fc043fe55389340c20e9c9681c0f58a347fd98d6f06f3db2518d6b26b9bc8b9243d9eb86a481d465288b54f7d514d229bc374d352cc1ce831",
          "sha256": "d0ffa3152acb49da118a453edaef3571238453efa520c30f001db5113d2a41e7",
          "sha1": "5aa254e716be74d63b7c2f1d84995f40ec2ee244",
          "md5": "90f6285a48b07f1651101c7165df48dd"
        }
      ]
    }
  ]
}
