{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.130",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.130.jar",
          "url": "alchemy-1.20.1-0.1.130.jar",
          "size": 1676227,
          "sha512": "af82f3d1a1b708fd99b0556e35782d1a89c43384f759a85ff4fcc56e079699ccd0350ef8cefcdfc2f762402e957ec4ffaa34cab67b2a7648ecc62147c3753515",
          "sha256": "24f43abbc24384f7a26fe9c58477b9013d2c58346bfb797db4e5c1c48f91c390",
          "sha1": "b806456a16e4d64d9e646aa5316efcbb3522a27e",
          "md5": "09121a3efcd907ac6be0eca5b6e2dd95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.130.jar",
          "url": "alchemy-1.20.1-0.1.130.jar",
          "size": 1676227,
          "sha512": "af82f3d1a1b708fd99b0556e35782d1a89c43384f759a85ff4fcc56e079699ccd0350ef8cefcdfc2f762402e957ec4ffaa34cab67b2a7648ecc62147c3753515",
          "sha256": "24f43abbc24384f7a26fe9c58477b9013d2c58346bfb797db4e5c1c48f91c390",
          "sha1": "b806456a16e4d64d9e646aa5316efcbb3522a27e",
          "md5": "09121a3efcd907ac6be0eca5b6e2dd95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.130-sources.jar",
          "url": "alchemy-1.20.1-0.1.130-sources.jar",
          "size": 1660436,
          "sha512": "9296bd80aabbe598c5a7b58e5ed24db9876bc8cfb47d5e6ac433d171f5bbbc097fd67503d54095965e448b1314962a082bedf3ce8ceab4bc14ef9fbffcf80a8d",
          "sha256": "426ea01635923548e7d060b334b516033ea6b5e45cd79f617434643e7a192204",
          "sha1": "bf9bc25e8fb14d3eb99f7d489971982a2923d576",
          "md5": "9c019d2dd9140a0d30c994bdd77ed623"
        }
      ]
    }
  ]
}
