{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.7-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.7-Fabric.jar",
          "url": "maple-1.20.1-1.3.7-Fabric.jar",
          "size": 1179518,
          "sha512": "53e213305956a7e621eb6fcbd1f5f8c292ee4b77d0e05d68afb2166a176b403e24e0f559d9142bcd5099e9922f3d980c64e3c979cdc766c115446860d788071f",
          "sha256": "e581a19ffed0ae7ce898032543214f92a69f1607bedbe97c0781a819a96f7ee5",
          "sha1": "c4831f2a96f9726ea9d25699aa3ca1ec50f42e4a",
          "md5": "35b0b15bfda125a579f3acb211db062d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.7-Fabric.jar",
          "url": "maple-1.20.1-1.3.7-Fabric.jar",
          "size": 1179518,
          "sha512": "53e213305956a7e621eb6fcbd1f5f8c292ee4b77d0e05d68afb2166a176b403e24e0f559d9142bcd5099e9922f3d980c64e3c979cdc766c115446860d788071f",
          "sha256": "e581a19ffed0ae7ce898032543214f92a69f1607bedbe97c0781a819a96f7ee5",
          "sha1": "c4831f2a96f9726ea9d25699aa3ca1ec50f42e4a",
          "md5": "35b0b15bfda125a579f3acb211db062d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.7-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.7-Fabric-sources.jar",
          "size": 1116802,
          "sha512": "314a9c305915090d426331a6cc50f7161c3743f3301c4db3638dcd918b88f8c7f0d05a32703b567dd04cb235b251ebaa2cf370a3b5b247744dd1175ec220df28",
          "sha256": "79a312af45777667f53c8cafeed35fb0871194728e77adfa33dd99db3008ae56",
          "sha1": "fa18b63e98eb5cb1f8080630dbbb154651542901",
          "md5": "860f9868ee53052566b3a6de2d99fbb8"
        }
      ]
    }
  ]
}
