{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w02b-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w02b-Fabric.jar",
          "size": 1498199,
          "sha512": "3775514884f55950d947af9dd601bf189217b6760075bfe9131d799b285c60fe6aaab839e574b7376beee08c51bb6f58833c28542cf7a9ea471316c2abeda32f",
          "sha256": "020a12256440e6e9f1701c088970191ac124364fe247c1220cd216c538461e15",
          "sha1": "52e628e2e2a86d7b1871bce9f217e0738118d91a",
          "md5": "b64f777730666c3d367d0bfc54bceea4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02b-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w02b-Fabric.jar",
          "size": 1498199,
          "sha512": "3775514884f55950d947af9dd601bf189217b6760075bfe9131d799b285c60fe6aaab839e574b7376beee08c51bb6f58833c28542cf7a9ea471316c2abeda32f",
          "sha256": "020a12256440e6e9f1701c088970191ac124364fe247c1220cd216c538461e15",
          "sha1": "52e628e2e2a86d7b1871bce9f217e0738118d91a",
          "md5": "b64f777730666c3d367d0bfc54bceea4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02b-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w02b-Fabric-sources.jar",
          "size": 1482174,
          "sha512": "1b792a42ca3cc983af9c46bda88cedd8c1be66b8b150c9007fc2cad810abaf677100702015b2d411926e82b5b27622f50ab2860eea71d6ce5b28db939f458601",
          "sha256": "0d9ae5632a1aac69f405b7274615c664a8b85e6b52f0c6ae74b27e5f9eef29f3",
          "sha1": "9e6424112954b14b140e5c1772f6f3628a8af75b",
          "md5": "59914dea6baefd0c64f5a1454ad22de8"
        }
      ]
    }
  ]
}
