{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta1-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta1-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta1-Fabric.jar",
          "size": 1013287,
          "sha512": "fcac3bed30a02a0ff15c1592b8ab8d24b2518acab82ce712aba616d523c6be984327869bdfd79f32c370082fb234a5b5d805f29478338e77b4dcefae4eb11a8f",
          "sha256": "12931cf96ae44e69b00b5d9ff5bb63cd11dfaf312de73897330179e9a148be20",
          "sha1": "553392c1b9486f8da4b6e599754a164e2886809d",
          "md5": "7f9a66a8555142bbcc7468734fdb37fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.1+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.0.169"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta1-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta1-Fabric.jar",
          "size": 1013287,
          "sha512": "fcac3bed30a02a0ff15c1592b8ab8d24b2518acab82ce712aba616d523c6be984327869bdfd79f32c370082fb234a5b5d805f29478338e77b4dcefae4eb11a8f",
          "sha256": "12931cf96ae44e69b00b5d9ff5bb63cd11dfaf312de73897330179e9a148be20",
          "sha1": "553392c1b9486f8da4b6e599754a164e2886809d",
          "md5": "7f9a66a8555142bbcc7468734fdb37fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta1-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta1-Fabric-sources.jar",
          "size": 944391,
          "sha512": "17118c826f545933599fe68dc16dba5f6d95033fecf97f36638126c75fe15196f23a9de2bea1be14cc1058b6ff5eb6263fd1cffc4b1ef27ef82c69586e37dfdb",
          "sha256": "eaa328e7a0e2fd92d518273d877ef6d19a4e2603d1eede9df1fb6fbd7a0d391f",
          "sha1": "747ed1fd7ebbfb8d62bd6e9112c9afa8c0524d39",
          "md5": "725c3489ed11d6af4f2afeb097604d5d"
        }
      ]
    }
  ]
}
