{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "GrowableOres",
    "version": "1.3.4-1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.4-1.20.1.jar",
          "url": "GrowableOres-1.3.4-1.20.1.jar",
          "size": 223134,
          "sha512": "5594dce8588004512f4baa2d271bfb67d374125199530b45eb27180dfda32f3e3d42a6d3340b06db9ed3998b64a1e0e07a0b2537a42b7dd6198078046531e6cd",
          "sha256": "9604d9796a15527980e8880dc9cc8264e34d5130782ece7ddf2c7bf72a50984d",
          "sha1": "8253b0a017e5227fb383f192dd3bc508a01db7d7",
          "md5": "209c52869b2c3e104be074bc2fb36905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "teamreborn",
          "module": "energy",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.85.0+1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "reborncore-237903",
          "version": {
            "requires": "4582416"
          }
        },
        {
          "group": "curse.maven",
          "module": "techreborn-233564",
          "version": {
            "requires": "4582415"
          }
        }
      ],
      "files": [
        {
          "name": "GrowableOres-1.3.4-1.20.1.jar",
          "url": "GrowableOres-1.3.4-1.20.1.jar",
          "size": 223134,
          "sha512": "5594dce8588004512f4baa2d271bfb67d374125199530b45eb27180dfda32f3e3d42a6d3340b06db9ed3998b64a1e0e07a0b2537a42b7dd6198078046531e6cd",
          "sha256": "9604d9796a15527980e8880dc9cc8264e34d5130782ece7ddf2c7bf72a50984d",
          "sha1": "8253b0a017e5227fb383f192dd3bc508a01db7d7",
          "md5": "209c52869b2c3e104be074bc2fb36905"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GrowableOres-1.3.4-1.20.1-sources.jar",
          "url": "GrowableOres-1.3.4-1.20.1-sources.jar",
          "size": 191897,
          "sha512": "eac2c55647476c1c27b2ea2a378914de41d29cb3b7108f0b2c9062e490430a5f88d13cfc4bfaa470cd6b54512f03fb77b4c24c0f9944aa180a83c07c1bf9535d",
          "sha256": "6fde0abf213a7ddbaed0a8d6bf006761e3c86d353b6564da3de9045928176824",
          "sha1": "6b7b2bee5d6cd8070b750151b1341e83d5fbe39c",
          "md5": "58a2fdee6e14433896be6fbc1c620cbb"
        }
      ]
    }
  ]
}
