{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.108",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.108.jar",
          "url": "alchemy-1.20.1-0.1.108.jar",
          "size": 1584647,
          "sha512": "561663ad0160dbc7c87379db2f9386f9aea647ce531910c718d283ea532354d692104e23bfe51f64c7776b7a7ce3c4ded9b6327602ff6518737055f1a4ca185d",
          "sha256": "69c90c36dcde5520307b8251d47a34d54ff0233cbdeed9581c51775257bd8f73",
          "sha1": "9c8a32a4c8c8a31f6e93cd4873694e805ad8e78c",
          "md5": "a861cae0755e7f4fce68c65342d13bb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.108.jar",
          "url": "alchemy-1.20.1-0.1.108.jar",
          "size": 1584647,
          "sha512": "561663ad0160dbc7c87379db2f9386f9aea647ce531910c718d283ea532354d692104e23bfe51f64c7776b7a7ce3c4ded9b6327602ff6518737055f1a4ca185d",
          "sha256": "69c90c36dcde5520307b8251d47a34d54ff0233cbdeed9581c51775257bd8f73",
          "sha1": "9c8a32a4c8c8a31f6e93cd4873694e805ad8e78c",
          "md5": "a861cae0755e7f4fce68c65342d13bb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.108-sources.jar",
          "url": "alchemy-1.20.1-0.1.108-sources.jar",
          "size": 1569913,
          "sha512": "4ae89fa20bd2d3cc4c73de69deab589b974927d424ae897d8b329291ecd1ad65200ecb0682f2fa28eebd53445cc597a98580d763d7099c09e410e85033d8f0bb",
          "sha256": "9d16b27ed27dce32707d264285e0857f2c3d2ce28774030339590e2921b7a2bd",
          "sha1": "5109c625ccc12851ab4e50e1587df31169af4b4c",
          "md5": "802a50e3865603af80c7ee38725ef37f"
        }
      ]
    }
  ]
}
