{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w04a-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04a-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04a-Fabric.jar",
          "size": 1617300,
          "sha512": "948768f93c1711f4eb6f96eead392b250d5a011479de79f523dc7b85a78b3718e8b53d95ab1149084268063fade93860c5b6053bf4b01fdb8c1f745798c7b910",
          "sha256": "6445e89899249c5a529dadfa1c6b27d08395875c0411951878b554901a4fda47",
          "sha1": "6b7c76a56aa7dcbae3b441adb431e89c61c23710",
          "md5": "c514a93cf4b7df255021408ebb57d1a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04a-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w04a-Fabric.jar",
          "size": 1617300,
          "sha512": "948768f93c1711f4eb6f96eead392b250d5a011479de79f523dc7b85a78b3718e8b53d95ab1149084268063fade93860c5b6053bf4b01fdb8c1f745798c7b910",
          "sha256": "6445e89899249c5a529dadfa1c6b27d08395875c0411951878b554901a4fda47",
          "sha1": "6b7c76a56aa7dcbae3b441adb431e89c61c23710",
          "md5": "c514a93cf4b7df255021408ebb57d1a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w04a-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w04a-Fabric-sources.jar",
          "size": 1605108,
          "sha512": "5874e888a6c233fe6019ead1e393401dfe85ba41f79c6731b9b390db26534ae94709c39cb98496b786701b01d3dba899d38ce132ec2f1cd7675cbb72e4cc2dcc",
          "sha256": "8f09fe321fb42e99d909cbaf7b73336fc334ad2d0e9d2e6bd84362ba8a6c0744",
          "sha1": "dc47b56917ee383d7cab9ce6e2e7002a51a4191a",
          "md5": "5ffbf017c8db08fb28bfa9f223c350e3"
        }
      ]
    }
  ]
}
