{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "alchemy",
    "version": "1.20.1-0.1.138",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.138.jar",
          "url": "alchemy-1.20.1-0.1.138.jar",
          "size": 1693767,
          "sha512": "4f678feca44337e39f42acb6ac4dc80d7ea83371ba0a1aecb1e750f3e3052d2e26e482221efcddcb4d0354cc73d7cacc48b1b15d41bdcdc49a186fb61066339b",
          "sha256": "6e59738fd45bcd80a8bf8661a3d5725eef57cc248aaaf562bb3e155970f016f9",
          "sha1": "2f707f1c416b8c54c390638f1da7bf1c3820ac8e",
          "md5": "c9d915c1994d710d005a77954c7b6fd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "dev.emi",
          "module": "trinkets",
          "version": {
            "requires": "3.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.138.jar",
          "url": "alchemy-1.20.1-0.1.138.jar",
          "size": 1693767,
          "sha512": "4f678feca44337e39f42acb6ac4dc80d7ea83371ba0a1aecb1e750f3e3052d2e26e482221efcddcb4d0354cc73d7cacc48b1b15d41bdcdc49a186fb61066339b",
          "sha256": "6e59738fd45bcd80a8bf8661a3d5725eef57cc248aaaf562bb3e155970f016f9",
          "sha1": "2f707f1c416b8c54c390638f1da7bf1c3820ac8e",
          "md5": "c9d915c1994d710d005a77954c7b6fd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "alchemy-1.20.1-0.1.138-sources.jar",
          "url": "alchemy-1.20.1-0.1.138-sources.jar",
          "size": 1681080,
          "sha512": "7c11ba2c30bc57fe9a44199c564d846a0cf8bf6051e6d31ceb11e3a1e0ebd7d49d1a3197119bf74ecd876c5fcbd231d86c4bb41f4afe8a521770245fd08fdd23",
          "sha256": "38836e8fd7a4b46488ccdea1088b44eaa7ad56ab90a79dd8cfb1961c5c17a493",
          "sha1": "9721b20873f6d3de8a73a597cdf16f73a9aa08af",
          "md5": "8f244683ce27ff4365f527b96dcbff03"
        }
      ]
    }
  ]
}
