{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.19.2-1.3.6-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-common-api",
          "version": {
            "requires": "11.5.0.297"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric-api",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.6-Fabric.jar",
          "url": "maple-1.19.2-1.3.6-Fabric.jar",
          "size": 1021581,
          "sha512": "9a3bf5dbcead1179bdc4104bc18d3f3a8934bf42041445bf8ca864f1ad0c05f376111c3d27f9df517d9fcb1029b993a8a0395fc6c0346bb13a54f4f9e8446728",
          "sha256": "a252e7fb0d719d142a5b077bf7b12f6961d08b1a320ee1911bb329d9feae0ca8",
          "sha1": "82a3ae71f60765f2e228765b2d60cd3140466305",
          "md5": "aab0a4f1771645a722898596f1e1a7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.2"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.19.2-2.0.1.166"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.19.2-fabric",
          "version": {
            "requires": "11.5.0.297"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.19.2-1.3.6-Fabric.jar",
          "url": "maple-1.19.2-1.3.6-Fabric.jar",
          "size": 1021581,
          "sha512": "9a3bf5dbcead1179bdc4104bc18d3f3a8934bf42041445bf8ca864f1ad0c05f376111c3d27f9df517d9fcb1029b993a8a0395fc6c0346bb13a54f4f9e8446728",
          "sha256": "a252e7fb0d719d142a5b077bf7b12f6961d08b1a320ee1911bb329d9feae0ca8",
          "sha1": "82a3ae71f60765f2e228765b2d60cd3140466305",
          "md5": "aab0a4f1771645a722898596f1e1a7c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.19.2-1.3.6-Fabric-sources.jar",
          "url": "maple-1.19.2-1.3.6-Fabric-sources.jar",
          "size": 1071500,
          "sha512": "85745f984be02f82812e1a449fc121ad6f373841edcddd82e856b1aa2935cf54a6cdb5d1a9c7f8859a9f9b18119dc04568dc04130f9ef7b28d53f45988d6a66b",
          "sha256": "14f232393f25c767b685e8e237201e5215983a2b9d8a445c54c58f3ae3419df1",
          "sha1": "fd5461985230bea3b9dba687716462431654cb56",
          "md5": "9f3d3bb077a92e4515481efffaa9e9d1"
        }
      ]
    }
  ]
}
