{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "super_apple",
    "version": "1.9.1-1.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "super_apple-1.9.1-1.15.2.jar",
          "url": "super_apple-1.9.1-1.15.2.jar",
          "size": 91697,
          "sha512": "64f2e0296a518ef3b6e12f3a4215322b5105a1d10a18a898c6dd92f1ed46d501d564d1eb7f2962982c0e9914fa4790b5e9b2c72730bb9aaee6882e23ebe45601",
          "sha256": "9e98c70f9046607814f9d7ff937ca119c6d1627dd7573adf06c109fb18d5e174",
          "sha1": "75de3a53376fab2440a04bd803d7e177bf97e404",
          "md5": "4414143477d82878a40405d2dd1a15da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.13"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        }
      ],
      "files": [
        {
          "name": "super_apple-1.9.1-1.15.2.jar",
          "url": "super_apple-1.9.1-1.15.2.jar",
          "size": 91697,
          "sha512": "64f2e0296a518ef3b6e12f3a4215322b5105a1d10a18a898c6dd92f1ed46d501d564d1eb7f2962982c0e9914fa4790b5e9b2c72730bb9aaee6882e23ebe45601",
          "sha256": "9e98c70f9046607814f9d7ff937ca119c6d1627dd7573adf06c109fb18d5e174",
          "sha1": "75de3a53376fab2440a04bd803d7e177bf97e404",
          "md5": "4414143477d82878a40405d2dd1a15da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "super_apple-1.9.1-1.15.2-sources.jar",
          "url": "super_apple-1.9.1-1.15.2-sources.jar",
          "size": 79193,
          "sha512": "7949a578462df23027baba6a6f3235c6bc0f95f11eb65707d2a24829cf3096d34aa22b94a3fa1591bba2f31d68d8d7c077018d74a9425f35fc25363b132910e8",
          "sha256": "4787dfd19af3a35789097db87497c8b60673cfd0d3640ffae30f562661d134a5",
          "sha1": "aa040829de56cce54a09854489ec7bd34fcf6759",
          "md5": "6a72985615dda3e610ee44cd03652352"
        }
      ]
    }
  ]
}
