{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.0.25w02c-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02c-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w02c-Fabric.jar",
          "size": 1571181,
          "sha512": "deccb92bfd467f2e903769892b132a9fd518ac89e44e43c6e08a95bc60c1ebc22d08acaaf95c7c7bd09d6a3b7192f24ad49eb75733bb27434e12831e94c1f427",
          "sha256": "bc32def3ee60394117bf2c4fe2d08eaa75d19a9029fe1d50c046806e9e8c0428",
          "sha1": "2a6a90d22a6a72e91a56a9aca63312c033632d13",
          "md5": "01d4ac1a1ed277ce3c1ecc3cf0f1a88d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02c-Fabric.jar",
          "url": "maple-1.20.1-1.4.0.25w02c-Fabric.jar",
          "size": 1571181,
          "sha512": "deccb92bfd467f2e903769892b132a9fd518ac89e44e43c6e08a95bc60c1ebc22d08acaaf95c7c7bd09d6a3b7192f24ad49eb75733bb27434e12831e94c1f427",
          "sha256": "bc32def3ee60394117bf2c4fe2d08eaa75d19a9029fe1d50c046806e9e8c0428",
          "sha1": "2a6a90d22a6a72e91a56a9aca63312c033632d13",
          "md5": "01d4ac1a1ed277ce3c1ecc3cf0f1a88d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.0.25w02c-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.0.25w02c-Fabric-sources.jar",
          "size": 1564177,
          "sha512": "3b924eb96651cfcdc55db3b7dc82b760ec64ba6b2a1c364df403a0d5af0a5625eecb4725b122928b6f4d4b4fbb48209cf6e8f66a2ee4116b4613a4a4ee7db753",
          "sha256": "b0078ec795d04a786fb21d964827a0aea222dd7d7ad5581a817966ee60dd5179",
          "sha1": "d77ea67d9c1aec7d28acfc613c45e38a3350d8be",
          "md5": "6e7cc84212f0a4dafcb4989bfe4314f3"
        }
      ]
    }
  ]
}
