{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.4.12-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.12-Fabric.jar",
          "url": "maple-1.20.1-1.4.12-Fabric.jar",
          "size": 1993481,
          "sha512": "cf648711b97628e41d716ed216f3d098609be3fe479e7ccfd17a41bfec58d5c0d78954da3eba77e62cd64a64c4771245bc4b6399b5836b076e3032122a6866c2",
          "sha256": "4e181a25e9825b8b619f6261a40ebf25aeee0953a145f89a7ce5ec044e70d771",
          "sha1": "14cf78301ec5cec240306a8e6700f425c640c53b",
          "md5": "637a2fb4a9faa54c864ecc3380a371a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "12.1.785"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.4.12-Fabric.jar",
          "url": "maple-1.20.1-1.4.12-Fabric.jar",
          "size": 1993481,
          "sha512": "cf648711b97628e41d716ed216f3d098609be3fe479e7ccfd17a41bfec58d5c0d78954da3eba77e62cd64a64c4771245bc4b6399b5836b076e3032122a6866c2",
          "sha256": "4e181a25e9825b8b619f6261a40ebf25aeee0953a145f89a7ce5ec044e70d771",
          "sha1": "14cf78301ec5cec240306a8e6700f425c640c53b",
          "md5": "637a2fb4a9faa54c864ecc3380a371a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.4.12-Fabric-sources.jar",
          "url": "maple-1.20.1-1.4.12-Fabric-sources.jar",
          "size": 2006164,
          "sha512": "23c0818de3f81e2c2974156fc88a8f363e1baf982a46af93fc1ee7559b4ccb8159a921624f12e8c5c2acb7363d7441a60533290bf6ac02061c8409a1de9b7a30",
          "sha256": "be5f8a8dd493dfadc09e0c6753647555257c89ec21c38ffcd2a6a5fb2649f3e4",
          "sha1": "55765b7ad300b4ca9beb1dccb5973f09f3bdfe24",
          "md5": "9d1a91b41546b743debc6bda6ea1cfcd"
        }
      ]
    }
  ]
}
