{
  "formatVersion": "1.1",
  "component": {
    "group": "com.skniro",
    "module": "maple",
    "version": "1.20.1-1.3.0-Beta12-Fabric",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta12-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta12-Fabric.jar",
          "size": 1137195,
          "sha512": "799c806846df7202a268d07c2f15ab1007cad7a0dee8d0f65f4f0421d841b5411f7397afb4b361101da4adbd074c2794b80fa78590e73a6385402180397eb067",
          "sha256": "0f3192819266f11bd46dd57c3f4cfe6bbcd8563e92644627b5ad760ab33de82b",
          "sha1": "df46c7e7a31c8e63fada036d36a6f711438b1d2b",
          "md5": "e0dd168e53a9cb7f5e37dedc1d6c446f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.llamalad7.mixinextras",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.2.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.2+1.20.1"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.1-3.0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta12-Fabric.jar",
          "url": "maple-1.20.1-1.3.0-Beta12-Fabric.jar",
          "size": 1137195,
          "sha512": "799c806846df7202a268d07c2f15ab1007cad7a0dee8d0f65f4f0421d841b5411f7397afb4b361101da4adbd074c2794b80fa78590e73a6385402180397eb067",
          "sha256": "0f3192819266f11bd46dd57c3f4cfe6bbcd8563e92644627b5ad760ab33de82b",
          "sha1": "df46c7e7a31c8e63fada036d36a6f711438b1d2b",
          "md5": "e0dd168e53a9cb7f5e37dedc1d6c446f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "maple-1.20.1-1.3.0-Beta12-Fabric-sources.jar",
          "url": "maple-1.20.1-1.3.0-Beta12-Fabric-sources.jar",
          "size": 1070813,
          "sha512": "f07536722c9607b1a22a5761543fea6cee8bbda65ff6e758df095b165d5c3c31842ab3895f07207556ca55f8f31e45094f0876b4e6183bdd91f972a6082f13ff",
          "sha256": "6e9bc2e428e5a565f0f5bcd9531821050f7b2f601d660b105f94aa75d554dc4d",
          "sha1": "50e04a089bd458ab68992964df0a15ce36c24578",
          "md5": "6602ddb75ee8dbbfaf6157471f933744"
        }
      ]
    }
  ]
}
